### ISSUE TITLE
Wrong typing for custom resolver root

### ISSUE THREAD

**Issue by P4sca1** [graphql-nexus/nexus-plugin-prisma#1004]
0.27.0 broke the typing.
See https://github.com/graphql-nexus/nexus-plugin-prisma/commit/005972caa9107b96a6e2dcd276f209830c66f574#r45144765

**Comment by mingchuno** [comment]
I encounter the same issue too...

**Comment by P4sca1** [comment]
@jasonkuhrt Was the typing changed by mistake or what was the intend behind it?

**Comment by jasonkuhrt** [comment]
Hey @P4sca1 I don't think this change was intended. PR welcome!

**Comment by P4sca1** [comment]
Alright, here it is @jasonkuhrt:
https://github.com/graphql-nexus/nexus-plugin-prisma/pull/1020
