### ISSUE TITLE
Support for prisma 2.15.0

### ISSUE THREAD

**Issue by BernardoQuina** [graphql-nexus/nexus-plugin-prisma#1029]
Hey, 
I wanted to test out some new prisma features, but since I'm getting this warning I was a little reluctant. 

"Warning: nexus-plugin-prisma@0.28.0 does not support @prisma/client@2.15.0. The supported range is: `2.14.x`. This could lead to undefined behaviors and bugs."

Could someone clarify to me what are the plans for a future release that supports prisma 2.15.0?
Thanks.

**Comment by ben-walker** [comment]
There's a branch called `renovate/prisma` which always includes a commit with the latest prisma version.

Typically it's only a day or two before this branch gets fixed/merged, and then there'll be a new release you can use that'll support 2.15.0!

Also it looks like GitHub Actions failed on 2.15, which is enough for me to hold off on the upgrade for now.

**Comment by adarnon** [comment]
Any news? It's been a long while... Usually the update happens in a couple of days

**Comment by Kuhave** [comment]
look at this: #1039

**Comment by ajRiverav** [comment]
Does https://github.com/graphql-nexus/nexus-plugin-prisma/pull/1033 close this issue?

**Comment by P4sca1** [comment]
> Does #1033 close this issue?

Yes, this plugin is compatible with Prisma versions up to 2.19 atm.

**Comment by ajRiverav** [comment]
cc @ben-walker
