### ISSUE TITLE
N + 1 Problem when using crud.

### ISSUE THREAD

**Issue by omerman** [graphql-nexus/nexus-plugin-prisma#1043]
I have this simple setup --> https://github.com/omerman/prisma-nexus-simple-starter
Prisma & nexus & prisma-nexus with logs for queries.
2 entites -> Post & Comment.

If you add 2 different posts, you will see that when seeking posts there will be a query fired per post for his comments.
Its kind of unreasonable. Am I missing something? Is there a fix for it?

Thank you guys, awesome work!

Omer

**Comment by darrylyoung** [comment]
I imagine your issue is related to [this](https://github.com/prisma/prisma/issues/5274) Prisma issue. As of now, you can avoid it by using Prisma `2.14.0` as the problem is in `2.15.0` (the version you're using) and `2.16.0`.

**Comment by omerman** [comment]
@darrylyoung Thank you for your response. I wish I could find 2.14.0, I couldn't locate it using npm/yarn install. Couldnt find it in npm.. kind of annoying, do you happen to have any ideas?

**Comment by omerman** [comment]
@darrylyoung 
Anyways.. I'll close the issue here. If you know how I can get my hands on 2.14.0, let me know please.. I couldn't find a way.
Thanks for the help :)

**Comment by darrylyoung** [comment]
Hi, @omerman. In your repository, try the following 3 commands:

```
yarn add @prisma/client@2.14.0
yarn add nexus-plugin-prisma@0.28.0
yarn add -D @prisma/cli@2.14.0
```

This will pin your Prisma dependencies to `2.14.0` and the plugin to `0.28.0`.

**Comment by omerman** [comment]
Yessss it works :) Thank you @darrylyoung, I couldnt find it becase I looked for `prisma@2.14.0` instead of the old `@prisma/cli` Thank you so much :)

**Comment by darrylyoung** [comment]
No problem! Glad it worked. :)
