### ISSUE TITLE
[nexus-prisma-generate] Allow to put prisma.yml in a custom folder

### ISSUE THREAD

**Issue by abathellier** [graphql-nexus/nexus-plugin-prisma#111]
I'm testing Nexus and trying to migrate an existing application. My prisma.yml file is in a `database` folder with other files related to Prisma:
- datamodel.graphql
- docker-compose.yml
- prisma.yml
- seed.graphql

When i try to generate types with: 
```bash
nexus-prisma-generate --client ./src/generated/prisma-client --output ./src/generated/nexus-prisma
```
i have the following error: 
```
Could not find `prisma.yml` file
```

While searching through the code, I found that Nexus-Prisma-generate only allows you to put prisma.yml in the **root** directory or in a **prisma** directory:

```js
function findPrismaConfigFile(): string | null {
  let definitionPath: string | null = path.join(process.cwd(), 'prisma.yml')

  if (fs.existsSync(definitionPath)) {
    return definitionPath
  }

  definitionPath = path.join(process.cwd(), 'prisma', 'prisma.yml')

  if (fs.existsSync(definitionPath)) {
    return definitionPath
  }

  return null
}
```
It would be better allow the user to define the prisma.yml path with a parameter to nexus-prisma-generate, perhaps like this:
```bash
nexus-prisma-generate --prisma ./database/prisma.yml --client ./src/generated/prisma-client --output ./src/generated/nexus-prisma
```

**Comment by Weakky** [comment]
Hey,

Is this blocking for you right now? #86 should soon land anyway, removing the need to input the `prisma.yml` as the command will be launched from it

**Comment by abathellier** [comment]
@Weakky no it’s ok I’ve just renamed my database folder to prisma. I can wait #86

**Comment by Weakky** [comment]
Awesome, closing now then 🙏
