### ISSUE TITLE
Mock prisma for jest unit tests?

### ISSUE THREAD

**Issue by abathellier** [graphql-nexus/nexus-plugin-prisma#112]
`makePrismaSchema` seems to inject prisma in the context while generating the schema. So when unit testing resolvers like that: 
```js
const context = {
  db: {
    user: jest.fn(),
    $exists: { user: jest.fn() },
    createUser: jest.fn(),
  }
}

const SIGNUP_MUTATION = /* GraphQL */ `
  mutation signUp($data: SignUpInput!) {
    signUp(data: $data) {
      email
    }
  }
`;

const user = {
  email: 'test.email.com',
};

context.db.createUser.mockResolvedValue({ ...user });

const res = graphql(schema, SIGNUP_MUTATION, null, context, { data: { idToken: 'TEST_TOKEN' } })

expect(res.data).toEqual({
  signUp: {
    ...user,
  },
});
```
The real Prisma seems to be called instead of the mocked one:
```
"message": "request to http://localhost:4466/default/local failed, reason: connect ECONNREFUSED 127.0.0.1:4466"
```

**Comment by Weakky** [comment]
`makePrismaSchema` doesn't inject the `prisma-client` in your context, it does use it directly. The `prisma-client` from your context comes from your GraphQL server instantiation, check out

https://github.com/prisma/nexus-prisma/blob/1564457cd108029c72f037ccf834b0076d448e7c/example/src/index.ts#L1-L8

Therefore if want to mock it, you have to both pass your mocked prisma client to your GraphQL server and `makePrismaSchema`

**Comment by abathellier** [comment]
But how can i pass a fake client? For instance if i pass:
```ts
const prisma = new Prisma({
  endpoint: ''
});
```
i get: 
```
"message": "Only absolute URLs are supported",
```
and if i pass a mocked `prisma-client`: 
```ts
const prisma = new Prisma({
  endpoint: '',
});

prisma.user = jest.fn();
prisma.$exists.user = jest.fn();
prisma.createUser = jest.fn();

export type MockedRecursive<T> = { [K in keyof T]: jest.Mocked<T[K]> } &
  jest.Mocked<T>;
const mockedPrisma = prisma as MockedRecursive<Prisma>;
```

i get:

```
"message": "prismaClient[parentName](...)[fieldName] is not a function"
```

So without passing the real `prisma-client` service, I don't really see how to do unit tests with `nexus-prisma`.....

**Comment by Weakky** [comment]
Hey 👋,

> I get: `prismaClient[parentName](...)[fieldName] is not a function`

This is because the prisma-client exposes functions to query the children of a top-level field. Meaning if you query `users { id posts { id ... } }`, it's going to result in something like `prisma.user({ id: root.id }).posts()` to fetch the posts of the users.

You just missed to mock some functions here, probably in `prisma.user.something = jest.fn()`

On a side note, this issue is related to the `prisma-client` itself and not with `nexus-prisma`.
I see you have created this issue for mocking the client https://github.com/prisma/prisma/issues/3898, this is most probably where it should be solved 🙌

**Comment by abathellier** [comment]
Thanks @Weakky!

If you look at [prisma/prisma#3898](https://github.com/prisma/prisma/issues/3898), the workaround given by @pantharshit00 was working for me with graphql first approach but no longer works with `nexus-prisma`. All my tests are broken now.

Before `nexus-prisma` and code first approach i was able to:
- mock only `prisma-client` fields required by my resolver and inject the mock into the context
```ts
const prisma = {}
prisma.user = jest.fn();
prisma.$exists.user = jest.fn();
prisma.createUser = jest.fn();
context = {
    prisma
}
const res = graphql(schema, MUTATION, null, context)
```
- mock by creating a fake prisma client (mostly for autocompletion)
```ts 
const prisma = new Prisma({
  endpoint: '',
});
prisma.user = jest.fn();
prisma.$exists.user = jest.fn();
prisma.createUser = jest.fn();
context = {
    prisma
}
const res = graphql(schema, MUTATION, null, context)
```
Now, `prisma-client` is strongly coupled to `nexus-prisma` and unit tests have become very difficult to implement. It is easier to set up only integration tests even if they are supposed to be complementary with unit tests.

Do you have any idea which `prisma-client` fields need to be mocked for nexus-prisma to work? All of them, I suppose?

Testing is fundamental to making a quality application, it could be interesting to have an example or best practices with `nexus-prisma` 🙏

**Comment by pantharshit00** [comment]
@Weakky Looks like we are unable to override the prisma client which is available via the context.

Can we do that somehow?

**Comment by Weakky** [comment]
An instance of the `prisma-client is both passed to the server and nexus-prisma.

- The one given to the server is only used if you need to access the prisma-client yourself through the context
- And the one given to nexus-prisma is used to resolve the types automatically

The client is not used in any weird way under the hood, I'm just auto-generating the calls that you would write if you had to do it manually.

Therefore, to answer the questions:

> Looks like we are unable to override the prisma client which is available via the context

The prisma-client available via the context is the once passed via your GraphQL Server. I am not altering any behaviour here, it should therefore be possible just like you used to do it before.

The only thing that changes is that you have to pass your mocked client **both** in `makePrismaSchema` and the instantiation of your GraphQL server

> Do you have any idea which `prisma-client` fields need to be mocked for nexus-prisma to work? All of them, I suppose?

That simply depends on which fields you're trying to tests. If you're trying to test your entire API, yes you need to mock the whole client. If you're trying to test such a query:

```graphql
{
  users {
    id
    name
    posts { id title }
  }
}
```

Then you probably need to mock something like: `client.users()`, `client.user(...).posts`.

**Comment by ThalesC** [comment]
So.. . the issue [prisma/prisma#3898](https://github.com/prisma/prisma/issues/3898) isn't there anymore? I'm a little confused about the concept behind mocking the `prisma-client` for unit testing anyway, is there any example I could use as reference? Thanks in advance!
