### ISSUE TITLE
Update peerDependencie nexus from 0.9.14 to 0.9.17

### ISSUE THREAD

**Issue by Oak-V** [graphql-nexus/nexus-plugin-prisma#136]
Hello Nexus-Prism Team!

I would like to request the nexus-prisma compatibility with the latest version of the Nexus main framework.

Also, I'd like to know at what level you plan to keep this tool compatible with Nexus. Nexus is in an early stage, it would be very important that my implementations receive the latest bugfixs and features

Graciously

**Comment by Weakky** [comment]
Hey there,

I just unpinned `nexus` version which should prevent this from happening in the future.

We plan to keep `nexus-prisma` up-to-date with nexus for quite a long time as this is now the official way of building GraphQL server with Prisma.

This is now fixed under `nexus-prisma@0.3.3` 🙏

**Comment by Oak-V** [comment]
Thank you!

I am aware that support will be fast.

Keep up the excellent work.

see you later
