### ISSUE TITLE
excluding fields syntax

### ISSUE THREAD

**Issue by kandros** [graphql-nexus/nexus-plugin-prisma#145]
At the moments looks like in order to exclude a field we have to explicitly declare all fields but the one we want to exclude

example: 

```
type User {
  id: ID! @unique
  email: String! @unique
  password: String!
}
```
in order to hide `password` we should do this:

```
const Post = prismaObjectType({
  name: 'User',
  definition(t) {
    t.prismaFields(['id', 'email'])
  },
})

...

export default makePrismaSchema({
  types: [Query, Mutation, Post],
   ...
}
```

some solution that comes to mind are:

allow `prismaObjectType` to get an object argument with `include`, and `exclude` key

```
const Post = prismaObjectType({
  name: 'User',
  definition(t) {
    t.prismaFields({'include': ['*'], exclude, ['password']})
  },
})
```

use negation `!` (i'm not sure this is actually doable in ts) and for every field add a negated version in the union typing

```
const Post = prismaObjectType({
  name: 'User',
  definition(t) {
    t.prismaFields(['*', '!password'])
  },
})
```

thoughts?

**Comment by Weakky** [comment]
Hey,

This is already doable using the `filter` property like so:

`t.prismaFields({ filter: ['password'] })`, which will expose everything but the password field.

Does that answer your question? 🙂

**Comment by kandros** [comment]
Yes, totally missed that doc part 🙈

Thanks
