### ISSUE TITLE
resolver.js: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by sirojinadias** [graphql-nexus/nexus-plugin-prisma#167]
> /node_modules/nexus-prisma/dist/resolver.js:14
>     if (datamodelInfo.embeddedTypes.includes(typeName)) {
>                                     ^
> 
> TypeError: Cannot read property 'includes' of undefined

Error found in version 0.3.4, solved by downgrading to 0.3.3

**Comment by Weakky** [comment]
Check out the release notes, you need to re-run `nexus-prisma-generate`

I forgot to add some validations for that property, I'll add it in the next release

**Comment by Weakky** [comment]
Fixed by https://github.com/prisma/nexus-prisma/commit/71a300c5e20150ce59d73508f37796d1765b5dda. Will be in the next release, closing now 🙂
