### ISSUE TITLE
support middleware

### ISSUE THREAD

**Issue by beeplin** [graphql-nexus/nexus-plugin-prisma#194]
https://github.com/prisma/nexus/issues/64 discusses the possibility of introducing middleware in `nexus` type definition to facilitate the re-usability of auth/validation logics in resolvers. Similarly, it would be nice if `nexus-primsa` could support middleware, maybe like this:

```js
const Query = prismaObjectType({
  name: 'Query',
  definition(t) {
    t.prismaFields(['user', { name: 'users', middleware: [middleware1, middleware2] }])
  },
})
```

**Comment by Weakky** [comment]
As nexus-prisma is just a wrapper around nexus, once nexus implements it, all the middleware will magically be able for nexus-prisma as well 🙂
