### ISSUE TITLE
nexus-prisma-generate clientPath escape on windows

### ISSUE THREAD

**Issue by mikaelkaron** [graphql-nexus/nexus-plugin-prisma#199]
I'm trying out [yoga2](https://github.com/prisma/yoga2) on Windows 10 and am running into (what I believe is) a path escape issue.

When running this:

```shell
npx nexus-prisma-generate --output ./.yoga/nexus-prisma
```

and later checking `./.yoga/nexus-prisma/datamodel-info.ts` I see that the `clientPath` is not correctly escaped:

```
  clientPath: '.yoga\prisma-client',
```

The correct path should be:

```
  clientPath: '.yoga\\prisma-client',
```

on a Windows system.

**Comment by Weakky** [comment]
Hey there, this should now be fixed under `nexus-prisma-generate@0.3.5`
