### ISSUE TITLE
Using prisma-binding instead of prisma-client

### ISSUE THREAD

**Issue by agonbina** [graphql-nexus/nexus-plugin-prisma#209]
This is a follow up to #81 

Currently nexus-prisma relies on the generated prisma-client from a prisma datamodel in order to resolve the client queries against the finaal schema (created using nexus and nexus-prisma).

As explained in my comment, this heavily limits the power and optimizations of the (older) client, ie prisma-binding, which deals a lot better with nested relationships in terms of optimizing the number of roundtrips/requests/database queries against your prisma service.

Pasting the original comment from that issue:
What if I want to use the prisma binding, ie the old (legacy?!) SDK) instead of the new prisma client in combination with `nexus-prisma`?

The "old SDK" is way more useful and optimized for usage in situations where you want to forward queries/mutations "as is" with some additional pre-processing (ex setting default arguments, or locking down values for specific arguments to the user session). 

Besides that, another drawback shows up when fetching nested relationships (one of the most powerful Prisma features), which is not optimized with the new prisma client as well as it is by using the prisma bindings in combination with fragments. 
Let's take this as an example data model: 
```
type Ship { title: String, user: User! }
type User { ships: [Ship!]! }
```
Say you want to fetch all users and their related ships after you have whitelisted the `users` (or `usersConnection`) query with `nexus-prisma`. What will happen is that this will issue a query for the list of users (ie `client.users()`) and then an additional query/request for fetching the ships for each user in that list, that is `client.users({ id }).ships()`, which means that in a list of 500 customers in a single query result, you would end up with 500 additional requests to get the related ships for each user. 
With prisma-binding this would result in one single round trip to your prisma service(which in turn will optimize the actual database query)

I do not understand what is the reasoning for using the prisma-client versus the prisma binding in the nexus-prisma package which is even officially recommended to be used for building graphql server clients that are typically proxying requests to prisma with some pre/post processing logic.

**Comment by agonbina** [comment]
From what I managed to dig through the implementation, it seems like the main touch point with the prisma client is in [resolver.ts](https://github.com/prisma/nexus-prisma/blob/master/packages/nexus-prisma/src/resolver.ts) where you dynamically make use of the prisma-client instance that is passed to the schema builder to "forward" the request.

Would it make sense to make this something you can pass as a configuration option, in which case it would use the prisma binding instance as opposed to the prisma client instance? I would be happy to look into adapting these changes if it makes sense from your perspective.

**Comment by AMO-MTSY** [comment]
Thank you @agonbina 
I still really don't understand why prisma team are pushing prisma-client (and "burying" prisma-binding)  in their new projects prisma-nexus and yoga2.
Maybe something will emerge at the long run.
I'm observing the evolution. Two days ago i tried the solution to get relay connection but i was scared literally.
Prisma-binding is an asset for you guys: don't bury it please

**Comment by agonbina** [comment]
Closing this issue because it does not seem like this is ever going to be reviewed/considered by the maintainer.
