### ISSUE TITLE
Suggested recipe to implement Interfaces and Unions?

### ISSUE THREAD

**Issue by faurehu** [graphql-nexus/nexus-plugin-prisma#223]
I'm currently implementing nexus-prsima into my graphql-yoga server. I can't figure out how to make it so when fetching an object by interface, have these objects be instances of the classes that implement the interface.

Here's my Prisma datamodel:
```
type Item {
  # interface
  id: ID! @unique
  mnemonic: String
  description: String
  factor: Factor!
  minimumUnitsForSale: Int!
  # custom fields: box item
  unitsPerBox: Int
  canBeUnboxed: Boolean
  minimumAtomicUnitsForSale: Int
}
```

and this is currently my server schema (without nexus):

```
interface Item {
  id: ID!
  mnemonic: String
  description: String!
  factor: Factor!
  minimumUnitsForSale: Int!
}

type BoxItem implements Item {
  id: ID!
  mnemonic: String
  description: String!
  factor: Factor!
  minimumUnitsForSale: Int!
  unitsPerBox: Int!
  canBeUnboxed: Boolean!
  minimumAtomicUnitsForSale: Int!
}

type UnitItem implements Item {
  id: ID!
  mnemonic: String
  description: String!
  factor: Factor!
  minimumUnitsForSale: Int!
}
```

I reckon that in order to reproduce the same schema with Nexus, I can write something like this:

```
const Item = interfaceType({
  name: "Item",
  definition: t => {
    t.id("id");
    t.string("mnemonic", { nullable: true });
    t.string("description");
    t.field("factor", { type: "Factor" });
    t.int("minimumUnitsForSale");
  }
});

const BoxItem = objectType({
  name: "BoxItem",
  definition: t => {
    t.implements(Item);
    t.int("unitsPerBox");
    t.boolean("canBeUnboxed");
    t.int("minimumAtomicUnitsForSale");
  }
});

const UnitItem = objectType({
  name: "UnitItem",
  definition: t => {
    t.implements(Item);
  }
});
```

However, I don't think this would be enough. If I query my server for an Item object, my server will know that it can get an item as-is from prisma but how will it know to return a UnitItem or a BoxItem?

I currently have this interfaces resolver that addresses that problem for me:

```
export const interfaces = {
  Item: {
    __resolveType(obj) {
      if (obj.factor === "BOX") {
        return 'BoxItem'
      } else {
        return 'UnitItem'
      }
    }
  }
}
```

How can I reproduce this with Nexus? Does it also have a `___resolveType` handler? 

Thanks

**Comment by Weakky** [comment]
Hey there,

Check out this nexus example: https://github.com/prisma/nexus/blob/49b4ac2f9aedeb5b30463c1d198d9c7072d23da9/examples/star-wars/src/graphql/character.ts#L23

You can use `t.resolveType` on the interface type 🙌

**Comment by faurehu** [comment]
Cheers
