### ISSUE TITLE
Creating new object that is not Mutation, Query or datamodel in prisma

### ISSUE THREAD

**Issue by ryankauk** [graphql-nexus/nexus-plugin-prisma#224]
Hey I'm starting to implement nexus-prisma and ran into an issue. I'm trying to create a new object with prismaObjectType and when I specify a name, since it's not Mutation, Query or a name of a datamodel in prisma it throws and error. If I use objectType I can create a new object but don't receive any types from args, or return type in resolver. Am I doing this wrong?

**Comment by ryankauk** [comment]
Here's an example

```typescript
const CouponsMutations = objectType({
  name: CouponNameSpace.Mutations,
  definition(t) {
    t.field('redeemCoupon', {
      type: 'Coupon',
      args: {
        businessId: idArg({ nullable: false }),
        qrCodeData: stringArg({ nullable: false })
      },
      resolve: async (parent, { code }, { auth, prisma }) => {}
    });
  }
});
```

the use of code should throw an error but it doesn't because it's reading args as any as well as the return type.

My assumption is because I'm using makePrismaSchema instead of makeSchema from nexus so maybe the nexus functions don't receive the types then?

**Comment by Weakky** [comment]
There are a couple of potential reasons for that issue:

- Either you forgot to export your type in `makeSchema/makePrismaSchema`
- Either you did not start/restart your graphql server and nexus could not generate the types
- Either VSCode just did not catch the generated types update, and you need to reload your IDE or restart its TS server

**Comment by Weakky** [comment]
Closing now, feel free to re-open if you still did not figure it out 🙌
