### ISSUE TITLE
Share prismaExtendType definitions error: prismaExtendType can only be used by `makePrismaSchema`

### ISSUE THREAD

**Issue by otrebu** [graphql-nexus/nexus-plugin-prisma#227]
Hi there,

Not sure if what I am trying to achieve is doable.

I would like to have some common mutations and queries between projects:

 `export const commonMutationField = prismaExtendType({ type: "Mutation", ...`

But I get this error when I run my graphql server:

`Error: prismaExtendType can only be used by `makePrismaSchema``

I don't fully understand why, as `commonMutationField` is used on `makePrismaSchema`.

Any ideas pleaseeee?

**Comment by Weakky** [comment]
All `prisma*` functions can only be used with `makePrismaSchema` because there are additional information needed for them to work, such as the `datamodelInfo` and the `prisma-client` instance

**Comment by otrebu** [comment]
Hi @Weakky thanks for your reply. But I import that `prismaExtendType` into a schema that then uses `prismaExtendType` with `datamodelInfo` and `prisma-client`. Shouldn't it work then?

**Comment by Weakky** [comment]
Oh, so `commonMutationField` is exported onto `makePrismaSchema({ types: ... })` ?

What are your `nexus` + `nexus-prisma` versions?

**Comment by otrebu** [comment]
I was using 
```"nexus": "^0.11.5",
 "nexus-prisma": "^0.3.5"```

I will try to update nexus to 0.11.6

**Comment by Weakky** [comment]
Also, make sure you have only **one** nexus-prisma version installed on your project

**Comment by otrebu** [comment]
ah! that might be it, I have these shared mutations in a separate shared among project folder. So I had to install `nexus-prisma` again.

**Comment by Weakky** [comment]
```
if (!(builder instanceof PrismaSchemaBuilder)) {
  throw new Error('prismaExtendType can only be used by `makePrismaSchema`')
}
```

That's the code responsible for throwing the error you're having. If you have different versions installed, the `instanceof` will fail, just like GraphQL with `GraphQLSchema`.

We need to loosen up that validation using `Symbol` instead

**Comment by otrebu** [comment]
Mmh I defensively have the same version now, but I get the same error. I did try to have a look at the code :)

So same version, but coming from 2 different node_modules folders should work?
