### ISSUE TITLE
prisma-client-lib subscription type integration issue with nexus

### ISSUE THREAD

**Issue by ryankauk** [graphql-nexus/nexus-plugin-prisma#228]
I tried to implement subscriptions and if I only return back the node it's fine because prisma.$subscribe
      .type()
      .node(); is type AsyncIterator<any>
but if I wanted everything with 
prisma.$subscribe
      .type()
it throws an error because the subscribe param on the subscription config on nexus is looking for AsyncIterator<any> and it's returning Promise<AsyncIterator<any>> and next doesn't exist on Promise
if i do prisma.$subscribe
      .type() as any though, everything works as it should

**Comment by sapkra** [comment]
Have you find any solution?

**Comment by sapkra** [comment]
I've created an issue and PR to fix this issue. You can also temporary add these modifications to your installed package if you want.
https://github.com/prisma/nexus/issues/119
https://github.com/prisma/nexus/pull/120

**Comment by Weakky** [comment]
Hey there 👋,

I just released https://github.com/prisma/nexus-prisma/releases/tag/v0.3.7 which enables better support for subscriptions.

It still doesn't fix the typings issue as this is related to nexus and the prisma-client but should offer you a better experience when working with subscriptions 🙏

https://github.com/prisma/nexus/pull/120 should be merged anytime soon!
