### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by bintoll** [graphql-nexus/nexus-plugin-prisma#245]
Hey! =) 
I tried to find something about error handling in nexus-prisma and prisma repository but without any result. I wonder to know, if there is a right way to handle errors with these packages. The reason why I ask - is because I tried to throw Error with custom message, but get the error message: "Cannot return null for non-nullable field".
I find that it is not really the right behavior, as long as the ordinary query resolver handle this error and provide it the for user output in graphQL under the filed "errors". Thanks!

**Comment by Weakky** [comment]
Hey there 👋,

Could you please provide a bit more context? (At least some code)

I just tried throwing in a resolver and the exception was properly caught by GraphQL

**Comment by bintoll** [comment]
@Weakky Sorry for opening this issue, this happened because of wrong written middleware. I fixed middleware and now the errors are handled in a right way! close it =)
