### ISSUE TITLE
upgraded to 1.31.1 nexus-prisma-generate generates syntax issue

### ISSUE THREAD

**Issue by ryankauk** [graphql-nexus/nexus-plugin-prisma#250]
After I run my prisma deploy, nexus prisma generates typescript file with now semicolons. Then when typescript-client runs it throws an error because it's expecting a semicolon

**Comment by Weakky** [comment]
Hey there,

Could you please provide a bit more context?

**Comment by ryankauk** [comment]
I figured out the problem. I don't know the exact reason but basically I upgrade my cli to 1.31.1 but didn't update my server yet (1.30.1). So it was still using the old datamodel. I updated my datamodel and and server and everything worked. I downgraded there after due to an issue with prisma admin. But after I reverted my cli back to 1.30.1 everything worked again. Seems like a backwards compatibility issue in 1.31.1 not being able to read the old datamodel.
