### ISSUE TITLE
Subscription type not generated

### ISSUE THREAD

**Issue by ludns** [graphql-nexus/nexus-plugin-prisma#267]
I am trying to use the Subscription feature in the new release (documented at [https://github.com/prisma/nexus-prisma/releases/tag/v0.3.7](https://github.com/prisma/nexus-prisma/releases/tag/v0.3.7)) and the type checking fails because the SubscriptionPayload type is not generated by nexus-prisma-generate. Basically there is no subscription payload type in NexusGenEnums. I upgraded nexus, nexus-prisma, and nexus-prisma-generate to the latest version w/o success.

**Comment by ludns** [comment]
Nevermind you actually need to force your server to boot and it will import the types. I am so used to not press Ctrl+S when my code is red haha

**Comment by homerjam** [comment]
I'm still getting this issue 🤔
