### ISSUE TITLE
Restricting query-able fields

### ISSUE THREAD

**Issue by LK** [graphql-nexus/nexus-plugin-prisma#273]
I have a `User` type with some public and some private fields on it. I define a custom `prismaObjectType` to explicitly whitelist the fields that I want to be public, and the generated `schema.graphql` correctly excludes the private fields from the `User` type. However, I want the `users` query to only allow API consumers to query based on fields that are public. Right now, the `UserWhereInput` input includes constraints on all fields, both public and private. What's the best practice on whitelisting query-able fields?

**Comment by LK** [comment]
`prismaInputObjectType` may be what I need (although I don't think this function is listed in the documentation), but looks like I still need to specify each field here explicitly (so `id`, `id_contains`, `id_ends_with`, and so on, rather than just specifying that I want all `id`-related fields). Is there a better way to tackle this?

**Comment by chaunceyau** [comment]
The generated api exposes ALL possible CRUD operations. To make certain fields (say email addresses), you must create a resolver in your server (e.g. graphql-yoga/apollo-server, NOT prisma server) that restricts access to the field. 

`export const User = prismaObjectType({
    name: 'User',
    definition(t) {
      t.prismaFields([
        'id',
        'name',
      ])
      t.string('email', {
        resolve: (parent, args, ctx) => {
     // Logic goes here. e.g. maybe only the actual user can view THIER email, no one else.
          return ""
        }
      })
    },
  })`
