### ISSUE TITLE
Question: Is it possible to hide prisma model?

### ISSUE THREAD

**Issue by Bjoernstjerne** [graphql-nexus/nexus-plugin-prisma#290]
Hello, searching the docu but did not find a solution:

I have a global prisma graphQL schema including admin specific types/mutations/queries what I would like to achieve is generating two different schemas. I know how I can remove queries or mutation but is there a possibility to remove types from the schema with nexus-prisma?

If not is there any other solution to get my different schemas with code first?

**Comment by Weakky** [comment]
Hey there 👋,

Do you mean two different schemas generated from the same endpoint? Or two different GraphQL API?

If you mean two different schemas from the same endpoint based on some condition (like user roles (eg: regular user, or admin)), then no, it's not possible yet. There's an issue about it here: https://github.com/prisma/nexus/pull/23, which mentions the concept of "visibility". We may have that one day, but it's not there yet 🙏

**Comment by Bjoernstjerne** [comment]
Thank you for your fast response. 
Yes two different outgoing schemas build from one internal is right. Are there any other solutions to not write the same code twice? I donnot think this is something special I want to achieve. Maybe anyone have a suggestion how to get this?
