### ISSUE TITLE
How do i create mulitple prismaInputObjectTypes from the same 'name'

### ISSUE THREAD

**Issue by luisgregson** [graphql-nexus/nexus-plugin-prisma#294]
I want to have 2 different mutations exposed to the client, which each expose a subset of the args available on the root prisma type.

Eg `updateUserBasicDetails` and `updateUserAddressDetails` mutations should both be derived from the prisma mutation of `updateUser`.

I can get one of them to work like this (it works with `ts-node`, and the playground shows the correct arg definitions, but there are some errors when running `tsc`):

```typescript
import { prismaExtendType, prismaInputObjectType } from 'nexus-prisma'
import { arg } from 'nexus'

export const updateUserBasicDetailsWhereArg = prismaInputObjectType({
  name: 'UserWhereUniqueInput',
  definition(t) {
    t.prismaFields(['id'])
  },
})

export const updateUserBasicDetailsDataArg = prismaInputObjectType({
  name: 'UserUpdateInput',
  definition(t) {
    t.prismaFields(['name'])
  },
})

export const updateUserBasicDetails = prismaExtendType({
  type: 'Mutation',
  definition(t) {
    t.field('updateUserBasicDetails', {
      ...t.prismaType.updateUser,
      args: {
        where: arg({
          type: updateUserBasicDetailsWhereArg,
        }),
        data: arg({
          type: updateUserBasicDetailsDataArg,
        }),
      },
      async resolve(_parent, args) {
        // resolve
      },
    })
  },
})
```

However, when i add another module, which creates `prismaInputObjectType`s from `UserWhereUniqueInput` and `UserUpdateInput`, i get the error: `Error: UserWhereUniqueInput was already defined and imported as a type, check the docs for extending types`.

I've tried using `t.implements` to see if i can clone the `prismaInputObjectType` but i can't get it to work.

Any ideas?

**Comment by KubaDotVaclavik** [comment]
@luisgregson Hi, did you solve this problem? Any workaround?
