### ISSUE TITLE
Use `nexus` instead of `@prisma/nexus`

### ISSUE THREAD

**Issue by Weakky** [graphql-nexus/nexus-plugin-prisma#304]
## Description

There are currently two missing features in nexus that led us to fork + publish that fork (as `@prisma/nexus`) in the meantime:

- https://github.com/prisma/nexus/issues/161
- https://github.com/prisma/nexus/pull/155
- Update nexus-prisma to use the changes made in nexus

Once both of these features are merged, we should remove all trace of `@prisma/nexus`,
in nexus-prisma for sure, but also in all the examples at https://github.com/prisma/photonjs

**Comment by jasonkuhrt** [comment]
In trying to jump on this, I am currently getting blocked on https://github.com/prisma/nexus/issues/156. I will try to resolve that upstream issue first.

To be clear about why: I am not sure its required. But I am not sure of much right now. My approach needs to remain conservative while I internalize general system dependencies and become able to intuit where issues arise from/or don't.

**Comment by jasonkuhrt** [comment]
There is still a bit of work left to do on the nexus side––or adjustments on nexus-prisma.

The gist is that this diff gets `nexus-prisma` tests passing with latest `nexus`:

[LOC Context](https://github.com/prisma/nexus/blob/8e3254d0232b7518f4eae9197e306c2e3b90f9e5/src/builder.ts#L1152)
```diff
-      block[methodName] = (...args: any[]) => {
-        const config = isList ? [args[0], { list: isList, ...args[1] }] : args;
-        return val.value.factory({
-          args: config,
-          typeDef: block,
-          builder: this,
-          typeName: block.typeName,
-        });
-      };
+      Object.defineProperty(block, methodName, {
+        get() {
+          return val.value.factory({
+            args: [],
+            typeDef: block,
+            builder: this,
+            typeName: block.typeName,
+          })
+        },
+        enumerable: true,
+      })
     });
   }
```

The nexus test suite also passes with this diff. I have opened [a PR](https://github.com/prisma/nexus/pull/205) to talk it through with @tgriesser.
