### ISSUE TITLE
Rename default read operations names (`findMany<Type>`, `findOne<Type>`)

### ISSUE THREAD

**Issue by Weakky** [graphql-nexus/nexus-plugin-prisma#308]
## Description

Currently, the query operations are named like so

(Given a `User` model)

```
t.crud.findManyUser()
t.crud.findOneUser()
```

We're thinking about renaming these and also enabling users to customize them.

### n°1 (current one)
```
t.crud.findManyUser()
t.crud.findOneUser()
```

### n°2
```
t.crud.allUsers()
t.crud.findUser()
```

### n°3
```
t.crud.users()
t.crud.user()
```

Feel free to vote or suggest other namings 🙌

**Comment by Hebilicious** [comment]
N°3 feels familiar to prisma1 users, is the shortest and is easy to grasp, my favorite by far.

**Comment by Weakky** [comment]
Hey @Hebilicious,

We've decided to go with n°3. It'll be available as a breaking change in the prisma cli release.

Thanks for your input, closing now 🙏
