### ISSUE TITLE
Error in documentation: updatesManyUsers

### ISSUE THREAD

**Issue by heymartinadams** [graphql-nexus/nexus-plugin-prisma#318]
[Documentation for Nexus with Prisma2](https://nexus.js.org/docs/database-access-with-prisma-v2) mentions `updatesManyUsers` (twice on page)... should it be `updateManyUsers`?

**Comment by Weakky** [comment]
Hey 👋,

This will get fixed once https://github.com/prisma/nexus/pull/173 is merged.

Thanks for raising the issue, closing now 🙏
