### ISSUE TITLE
Neither extendType, nor queryField/mutationField are working

### ISSUE THREAD

**Issue by psypath** [graphql-nexus/nexus-plugin-prisma#319]
I'm trying to leverage Nexus with Prisma2. Neither extendType, nor queryField/mutationField are working. Schema just ignores them as if I haven't defined them at all.

**Comment by Weakky** [comment]
Hey 👋,

I just tried `extendType` and `queryField`/`mutationField`, and they all work properly for me. Are you sure you exported them into `makeSchema({ types: [...] })` ?

**Comment by psypath** [comment]
@Weakky Yes, I'm sure. I can provide you my code as an example, but a bitlater.

**Comment by psypath** [comment]
@Weakky Seems like it works, indeed. 
I, probably, made a mistake trying to implement it in the previous time.
