### ISSUE TITLE
Cannot create mutations for Prisma models with custom field names for @createdAt prisma directive

### ISSUE THREAD

**Issue by ozimos** [graphql-nexus/nexus-plugin-prisma#325]
Prisma read-only fields with custom names using the @createdAt directive are not properly generated by nexus-prisma

**Steps to Reproduce**
Follow steps 1 -4 of the guide at https://nexus.js.org/docs/database-access-with-prisma#getting-started

The mutation below should run successfully
```
mutation {
  createUser (
    data: {
    	email: "nexus@prisma"
    	posts: {
        create: [
          {
            title: "strange"
          }
        ]
      }
    }
   
  ) {
    email
  }
}
```
Change the `createdAt` field on the datamodel  to `postedAt`
The datamodel should now look like this
```
type User {
  id: ID! @id
  email: String! @unique
  name: String
  posts: [Post!]!
}

type Post {
  id: ID! @id
  postedAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  published: Boolean! @default(value: false)
  title: String!
  content: String
  author: User!
}
```
run `prisma deploy --force`
running the same mutation above produces this error
```
{
  "error": {
    "errors": [
      {
        "message": "Field PostCreateWithoutAuthorInput.postedAt of required type DateTime! was not provided.",
        "locations": [
          {
            "line": 2,
            "column": 61
          }
        ]
      }
    ]
  }
}
```

**Comment by Powell-v2** [comment]
Same problem here. I circumvent this issue by passing an empty argument and later ignoring it in the resolver - but as you can imagine, that's a major nuisance.

Versions used:
```
prisma: 1.33
nexus-prisma: 0.3.7
prisma-client-lib: 1.33.0
```
