### ISSUE TITLE
DateTime scalar and filters

### ISSUE THREAD

**Issue by psypath** [graphql-nexus/nexus-plugin-prisma#330]
I noticed that if I do not use DataTime type in Prisma's file, the following error happens: 
`Error: Input Object type QueryFindManyUserFilter must define one or more fields.`

Then I checked what `QueryFindManyUserFilter` is like. Here it is:
 
```
QueryFindManyEventFilter {
  equals: DateTime
  gt: DateTime
  gte: DateTime
  in: [DateTime!]
  lt: DateTime
  lte: DateTime
  not: DateTime
  notIn: [DateTime!]
}
```

This is how I define Query.events field using Nexus:
`t.crud.findManyEvents({alias: 'events', filtering: true, ordering: true})`

And this is how my schema looks like eventually:

![image](https://user-images.githubusercontent.com/12710889/60756298-32068400-a026-11e9-9e98-02106e92aeff.png)

So:
- seems like QueryFindManyEventFilter should be named like DateTimeFilter. 
- it should be possible not to use DateTime type in Prisma's schema file

**Comment by jasonkuhrt** [comment]
Hey @victordombrovskiy could you clarify what you mean by:

> I noticed that if I do not use DataTime type in Prisma's file

**Comment by psypath** [comment]
Ok. Prisma allows to use DateTime as type of model properties in prisma file. If I have a prisma file, where there are models, which have properties of type DateTime - the aforementioned issue doesn't happen. But if all models have no property of type DateTime, I receive the error.

**Comment by jasonkuhrt** [comment]
I cannot reproduce. For example this works:

```ts
model User {
  id @id @unique @default(cuid())
}
```
```ts
objectType({
  name: 'User',
  definition(t) {
    t.model.id()
  },
})
queryType({
  definition(t){
    t.users({filtering:true})
  }
})
```
```gql
type Query {
  users(after: String, before: String, first: Int, last: Int, skip: Int, where: UserWhereInput): [User!]!
}

input StringFilter {
  contains: String
  endsWith: String
  equals: String
  gt: String
  gte: String
  in: [String!]
  lt: String
  lte: String
  not: String
  notIn: [String!]
  startsWith: String
}

type User {
  id: ID!
}

input UserWhereInput {
  AND: [UserWhereInput!]
  id: StringFilter
  NOT: [UserWhereInput!]
  OR: [UserWhereInput!]
}
```

**Comment by psypath** [comment]
I can't reproduce it as well now. So, probably, let's close it.
