### ISSUE TITLE
How do you get uuid() working?

### ISSUE THREAD

**Issue by chrisbull** [graphql-nexus/nexus-plugin-prisma#335]
I'm building out my prisma2 api. We use UUID's instead of cuid's. However, I'm getting the error `- Missing type UUID, did you forget to import a type to the root query?` when `yarn start`. 

Here is an example model: 
```
model User {
  id                  String                @default(uuid()) @id @unique
}
```

**Comment by ChristianJacobsen** [comment]
I can add that this also happens for `BatchedPayload` if you attempt to use `t.crud.updateManyUser` or `t.crud.deleteManyUser`, and their brethren. Works smoothly for `cuid()`.

**Comment by sjensenihi** [comment]
@ChristianJacobsen were you able to figure out an answer to this? I just ran into this problem too but I'm not sure where I'd import BatchPayload from.

**Comment by ChristianJacobsen** [comment]
@sjensenihi No I was not, unfortunately. But the team has recently hired someone to work full-time on `nexus-prisma`, so I guess this problem will be addressed soon.

**Comment by chrisbull** [comment]
Thank you @pantharshit00, months later and this still appears to be an issue. But your workaround worked (so far).

@divyenduz To reattempt this, just set any of your `@cuid` to `@uuid` and it will break
