### ISSUE TITLE
Nexus prisma is disconnecting from the query engine when any error is thrown

### ISSUE THREAD

**Issue by pantharshit00** [graphql-nexus/nexus-plugin-prisma#338]
Ref: https://github.com/prisma/prisma2/issues/113

Reproduction: https://github.com/prisma/prisma2/issues/113#issuecomment-515717357

Right now if you server throws any kind of error(like if invalid graphql SDL was received), nexus-prisma is disconnecting from the query engine causing subsequent calls to throw `Engine has already been stopped`.

**Comment by jasonkuhrt** [comment]
This was first but #340 has more info, will treat this one as a duplicate of that.
