### ISSUE TITLE
How to add query's arguments

### ISSUE THREAD

**Issue by beingtyson** [graphql-nexus/nexus-plugin-prisma#351]
I want to pick one random row from a list
```
export const Chicken = prismaObjectType({
  name: 'Chicken',
  definition(t) {
    t.prismaFields(['*']);
  },
})
```
```
export const ChickenQueries = prismaExtendType({
  type: 'Query',
  definition(t) {
    t.prismaFields(['chicken', 'chickens']);
  },
})
```
```
type Chicken {
  id: ID! @id
  brend: Brend!
  menu: String!
  type: ChickenType!
  taste: TasteType!
  img: String!
}
```

This 'Chikens' type has the arguments
where ,orderBy, skip, after, before, first, last

But, i want to add random argument
like this
```
query{
  chickens(Random:true){
    id
  }
}
```
is there any good way?

**Comment by Weakky** [comment]
Hey 👋,

Please have a look at the `t.prismaType` feature in the doc: https://nexus.js.org/docs/database-access-with-prisma#tprismatype

There's an example called `Use all the options, add more arguments with a custom resolver`

**Comment by melanke** [comment]
Hi, the doc link is broken, could you update? Thx
