### ISSUE TITLE
Typescript Error:Type error

### ISSUE THREAD

**Issue by HowardTangOvO** [graphql-nexus/nexus-plugin-prisma#356]
![image](https://user-images.githubusercontent.com/22932158/63220855-59727400-c1c2-11e9-8c37-9def097c10b5.png)
![image](https://user-images.githubusercontent.com/22932158/63220857-62634580-c1c2-11e9-8486-39ac797a7288.png)
![image](https://user-images.githubusercontent.com/22932158/63220859-6a22ea00-c1c2-11e9-9ec2-7b539ac0eca4.png)

```
Error:index.ts(46, 5): The expected type comes from property 'orderBy' which is declared here on type '{ where?: CaseWhereInput; orderBy?: CaseOrderByInput; skip?: number; after?: string; before?: string; first?: number; last?: number; }'
```
How to solve this problem?
Or did I do something wrong?

**Comment by jasonkuhrt** [comment]
Hey @HowardTangHw what was your resolution?

**Comment by HowardTangOvO** [comment]
HI,@jangerhofer
I used below code to fix it, but I'm not sure this is the right way.

![image](https://user-images.githubusercontent.com/22932158/63264131-e4379980-c2bc-11e9-916b-2819111d17f1.png)
