### ISSUE TITLE
Error in docs: ctx => photon instead of ctx => ctx.photon

### ISSUE THREAD

**Issue by deadcoder0904** [graphql-nexus/nexus-plugin-prisma#360]
I have downloaded `examples/graphql` from `photonjs` repo & in it, the following is shown:

```js
const nexusPrisma = nexusPrismaPlugin({
  photon: ctx => ctx.photon,
})
```

While in the [docs available here](https://nexus.js.org/docs/database-access-with-prisma-v2#examples), the following is shown:

```js
const nexusPrisma = nexusPrismaPlugin({
  photon: (ctx) => photon,
});
```

Which one is correct? Code in Photon or Docs of Nexus?

**Comment by Weakky** [comment]
Hey 👋, thanks for raising this. The correct one is the one from the example, the doc is wrong. We'll fix this soon!

**Comment by jasonkuhrt** [comment]
This was not a bug per se, just a difference in style. 

```
const photon = new Photon();

const nexusPrisma = nexusPrismaPlugin({
  photon: (ctx) => photon,
});
```

Getting it from lexical scope rather than off ctx. Confusing, but working.
