### ISSUE TITLE
Unknown prisma-client function for field Query.XXXXXXXXX

### ISSUE THREAD

**Issue by marticrespi** [graphql-nexus/nexus-plugin-prisma#369]
Hi,

I'm using nexus-prisma to modify some types and add some custom mutations, but I'm getting an error and I don't know why.

Here are what I'm using:

````
nexus                    0.11.6
nexus-prisma              0.3.5
prisma                   1.34.5
prisma-client-lib        1.34.5
````

And my sumarized index.ts looks like this;

````
   import { enumTypes } from './internal/enum-types';
   import { argsTypes } from './internal/args/';
   import { prismaObjectTypes } from './internal/prisma-object-types';
   import { objectTypes } from './internal/object-types';
   import { prisma } from './generated/prisma-client';
   import datamodelInfo from './generated/nexus-prisma'

  const Query = prismaObjectType({ 
    name: 'Query',
    definition: t => t.prismaFields(['*'])
  });

  const Mutation = prismaObjectType({ 
    name: 'Mutation',
    definition(t) {
      // Keep all the mutations
      t.prismaFields(['*']);

      // Add a custom mutation
      t.field('updateSchema', {
        type: 'UpdatedSchema',
        args: argsTypes.environmentArgs,
        resolve: (parent, { environment }, ctx) => {
         // ....
         // Irrelevant code
        }
      })

  const schema = makePrismaSchema({
    types: [Query, Mutation, objectTypes, prismaObjectTypes, enumTypes],
    prisma: {
      datamodelInfo,
      client: prisma,
    },
    outputs: {
      schema: path.join(__dirname, './generated/nexus/schema.graphql'),
      typegen: path.join(__dirname, './generated/nexus/nexus.ts')
    },
  });
  
  const server = new GraphQLServer(
    {
    schema: schema,
    context: ({ request }) => ({
      ...request,
      prisma
    })
  });

server.start(() => console.log(`Server is running on http://localhost:4000`));
````

When I try to get the Item_BillingAccounts from prisma server directly (I have it in docker at localhost:4467) it works perfectly.

![image](https://user-images.githubusercontent.com/6670879/63844150-f59d3780-c987-11e9-951e-9f1823fe51c0.png)

But if I want to get bypassing my node app running at localhost:4000  using `nexus-prisma` doesn't work.

`Unknown prisma-client function for field Query.item_BillingAccount`

![image](https://user-images.githubusercontent.com/6670879/63844287-35fcb580-c988-11e9-8a00-cc962c337f10.png)

My datamodel about this type:

````
type Item_BillingAccount @db(name: "Item_BillingAccount") {
  billingAccount: BillingAccount @relation(link: INLINE)
  createdAt: DateTime! @createdAt
  id: Int! @id(strategy: SEQUENCE) @sequence(name: "Item_BillingAccount_id_seq", initialValue: 1, allocationSize: 1)
  InvoiceBreakdowns: [InvoiceBreakdown]
  item: Item @relation(link: INLINE)
  updatedAt: DateTime! @updatedAt
  amount: Float!
  isPercentage: Boolean @default(value: true)
  order: Int!
}
````

Someone knows what I'm doing wrong or if it's a `nexus-prisma` bug or if I can fix easily?

**Comment by marticrespi** [comment]
Anyone?

I have updated `nexus` from `0.11.6` to `0.11.7` and `nexus-prisma` from `0.3.5` to `0.3.8` and it still happening the same!

**Comment by marticrespi** [comment]
@Weakky Could you tell me something about please?

**Comment by ghost** [comment]
Can you share the generated schema.graphql?

**Comment by marticrespi** [comment]
Hi @dillonparfitt 

Here is my prisma graphql schema generated by prisma
[prisma.graphql.txt](https://github.com/prisma/nexus-prisma/files/3595827/prisma.graphql.txt)

And here is my nexus graphql schema generated by nexus-prisma
[schema.graphql.txt](https://github.com/prisma/nexus-prisma/files/3595833/schema.graphql.txt)

Many thanks!

**Comment by ghost** [comment]
Can you try doing the same thing but changing the id to be type ID. Your datamodel would look like

```
type Item_BillingAccount @db(name: "Item_BillingAccount") {
  billingAccount: BillingAccount @relation(link: INLINE)
  createdAt: DateTime! @createdAt
  id: ID! @id(strategy: SEQUENCE) @sequence(name: "Item_BillingAccount_id_seq", initialValue: 1, allocationSize: 1)
  InvoiceBreakdowns: [InvoiceBreakdown]
  item: Item @relation(link: INLINE)
  updatedAt: DateTime! @updatedAt
  amount: Float!
  isPercentage: Boolean @default(value: true)
  order: Int!
}
```

**Comment by marticrespi** [comment]
Hi @dillonparfitt, If I change Int to ID and I try to redeploy the server it throws a validation error

`
Errors:
  Item_BillingAccount
    × The directive @sequence must only be specified for fields that are marked as id, are of type Int and use the sequence strategy. E.g. id: Int! @id(strategy: SEQUENCE).`

**Comment by dillonparfitt** [comment]
Hi, ok just as a quick test remove the sequence related data so your id would just be:

‘’’
id: ID! 
‘’’

**Comment by marticrespi** [comment]
Someone can help me?

**Comment by marticrespi** [comment]
Hi @Weakky, as I said you on slack by private message, now I have found out that for unknow reason it's renaming the function, in docker graphql is called `item_BillingAccounts` and in my nexus prisma generated client is `itemBillingAccounts`.. It's removing the underscore..

![image](https://user-images.githubusercontent.com/6670879/65032444-76c26b80-d943-11e9-959e-9a2a80356f4c.png)

![image](https://user-images.githubusercontent.com/6670879/65034299-0d445c00-d947-11e9-98f3-090db256e74b.png)

![image](https://user-images.githubusercontent.com/6670879/65034351-26e5a380-d947-11e9-9929-6f889ea08e39.png)


It only happens in the queries, the mutation name functions are ok with the underscore..

![image](https://user-images.githubusercontent.com/6670879/65033454-54c9e880-d945-11e9-8188-75faac129be5.png)

**Comment by marticrespi** [comment]
Closing, it's a typescript generator prisma bug.
