### ISSUE TITLE
After installing preview-9, unable to run Node.js server

### ISSUE THREAD

**Issue by malekjaroslav** [graphql-nexus/nexus-plugin-prisma#372]
After I installed preview-9, I am getting this error:

```
/node_modules/@generated/nexus-prisma/index.js:877
        return nexus_1.dynamicOutputProperty({
^
TypeError: nexus_1.dynamicOutputProperty is not a function
    at NexusPrismaBuilder.getCRUDDynamicOutputMethod
```

**Comment by malekjaroslav** [comment]
@divyenduz There doesn’t seem to be any new release since the merge

**Comment by divyenduz** [comment]
Yup, I just wanted to write the context on this issue, probably @jasonkuhrt will look into it shortly.

**Comment by jasonkuhrt** [comment]
> There doesn’t seem to be any new release since the merge

Hey @malekjaroslav, there [was](https://github.com/prisma/nexus/commit/90efe78322441213d37e2e4ebb1d4bdc782a8a0b). Are you already on that version of Nexus and still seeing this error?

**Comment by malekjaroslav** [comment]
@jasonkuhrt Yes I tried this one, but it did not work either. Doesn't the `nexus` dependency need to be updated within `nexus-prisma` / `@prisma/nexus`?

**Comment by chrisbull** [comment]
So even though I used the new `prisma2@2.0.0-preview-9.1` to scaffold the project, I was getting the same error. But when I rolled back to the `prisma2@2.0.0-preview-8` globally and locally, I am finally able to run `yarn start` without the error. So definitely is an issue between the versions.

**Comment by janpio** [comment]
Can you post the `npm list --depth=0` output for that project please?

**Comment by jasonkuhrt** [comment]
For a working example @malekjaroslav you can refer to https://github.com/prisma/nexus-prisma/pull/368. Note it is using `"prisma2": "^2.0.0-alpha.155",`.

**Comment by malekjaroslav** [comment]
Updating to those versions, omitting `@prisma/nexus` and using `nexus` instead,  solved the issue. `
```
    "nexus": "0.12.0-beta.9",
    "nexus-prisma": "0.0.1-beta.7",
    "prisma2": "2.0.0-alpha.160"
```

**Comment by jasonkuhrt** [comment]
@malekjaroslav thanks for bearing with us! 🙏

**Comment by gihrig** [comment]
@malekjaroslav's version changes and corresponding code changes worked for me with preview-10.

Question: Is using `nexus` and `nexus-prisma` in place of `@prisma-nexus` expected to be the preferred solution going forward?

**Comment by jasonkuhrt** [comment]
> Question: Is using nexus and nexus-prisma in place of @prisma-nexus expected to be the preferred solution going forward?

@gihrig yes 💯 pretend you never saw `@prisma/nexus` :)
