### ISSUE TITLE
DateTime scalar

### ISSUE THREAD

**Issue by psypath** [graphql-nexus/nexus-plugin-prisma#375]
If I use DateTime type in my Prisma2 schema, then a DateTime scalar is added to my GraphQL schema by Nexus. Seems like this scalar doesn't perform any validation and doesn't convert input value from string to an instance of Date. It actually does nothing at all. So, I either want to adjust it to do so, or replace it by my own DateTime scalar. But if I try to add my own DateTime scalar, I see the error:

`DateTime was already defined and imported as a type, check the docs for extending types`

How can I achieve my goal? 
Or there is a reason why it works this way and conversion is a bad idea?

**Comment by psypath** [comment]
@jasonkuhrt What you decided regarding this question? Just faced this issue again.

**Comment by jasonkuhrt** [comment]
Hey @siberian-man we're getting close, see https://github.com/graphql-nexus/nexus/issues/1028

**Comment by Weakky** [comment]
Hey @siberian-man, you can now add your own scalars to `nexus-prisma`, via the `scalars` options. You can read more about it in the configuration section here https://www.nexusjs.org/#/components/schema/plugins/prisma?id=configuration

Here's a small usage example:

```ts
import { nexusPluginPrisma } from 'nexus-prisma'
import { DateTime } from 'graphql-iso-date'

makeSchema({
  plugins: [nexusPluginPrisma({
    scalars: {
      DateTime: DateTime
    }
  })]
})
```
