### ISSUE TITLE
Prisma2: Pagination boolean doesn't work

### ISSUE THREAD

**Issue by ryands17** [graphql-nexus/nexus-plugin-prisma#376]
### Steps to reproduce
- While following the documentation for [Prisma 2](https://nexus.js.org/docs/database-access-with-prisma-v2) the pagination boolean value for creating an `objectType` doesn't seem to have any effect.

```ts
import { objectType } from '@prisma/nexus'

export const User = objectType({
  name: 'User',
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.email()
    t.model.posts({
      pagination: false,
    })
  },
})
```

The above code doesn't work as it still provides the pagination fields in the `schema.graphql` file. But converting it to the object notation solves the issue

```ts
import { objectType } from '@prisma/nexus'

export const User = objectType({
  name: 'User',
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.email()
    t.model.posts({
      pagination: {},
    })
  },
})
```

Also adding the boolean for the specific fields doesn't work

```ts
import { objectType } from '@prisma/nexus'

export const User = objectType({
  name: 'User',
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.email()
    t.model.posts({
      pagination: { first: true, skip: false },
    })
  },
})
```

The above gives the following output in `schema.graphql`
```graphql
type User {
  email: String!
  id: ID!
  name: String
  posts(first: Int, skip: Int): [Post!]
}
```

### Library versions
prisma2: `2.0.0-preview-7`
@prisma/nexus: `0.0.1`
nexus: `0.12.0-beta.6`

**Comment by jasonkuhrt** [comment]
Can you please update your deps to the latest versions. You can refer to the example in this repo.

**Comment by jasonkuhrt** [comment]
> The above code doesn't work as it still provides the pagination fields in the schema.graphql file. 

Confirmed this is still an issue with latest version. Easy to repro on the example app for example.

**Comment by ryands17** [comment]
@jasonkuhrt @Weakky This doesn't cover the boolean property for pagination, when we use `pagination: false`, it includes all the parameters.

**Comment by jasonkuhrt** [comment]
@ryands17 thanks for the catch, yep.
