### ISSUE TITLE
Prisma2 ordering property doesn't work on models

### ISSUE THREAD

**Issue by ryands17** [graphql-nexus/nexus-plugin-prisma#377]
### Steps

On adding the ordering property to the model, the compiler throws an error

```ts
import { objectType } from '@prisma/nexus'

export const User = objectType({
  name: 'User',
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.email()
    t.model.posts({
      ordering: true,
    })
  },
})
```

The following error is received in the terminal
```
Using ts-node version 8.3.0, typescript version 3.5.3
Error: Could not find ordering argument for User.posts
```

Even the internal ordering fields are also not working

```ts
import { objectType } from '@prisma/nexus'

export const User = objectType({
  name: 'User',
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.email()
    t.model.posts({
      ordering: { title: true },
    })
  },
})
```

### Library versions
prisma2: `2.0.0-preview-7`
@prisma/nexus: `0.0.1`
nexus: `0.12.0-beta.6`

**Comment by tgriesser** [comment]
You might have more luck opening this under this project: https://github.com/prisma/nexus-prisma - I believe the issue is specific to the `nexus-prisma` plugin.

**Comment by jasonkuhrt** [comment]
Can you please update your deps to the latest versions. You can refer to the example in this repo.

**Comment by jasonkuhrt** [comment]
You can see a [working example of ordering in the example](https://github.com/prisma/nexus-prisma/blob/24d4f27e5fff5650deaf6f60d351af0989e4165a/example/src/graphql/Blog.ts#L13). Just update to latest versions to get things working.

**Comment by nhuesmann** [comment]
@jasonkuhrt Thanks for the guidance, looks like examples/boilerplate must have been incorrect. I've switched to using `nexus` rather than `@prisma/nexus` and followed the example, can confirm filtering/order is working.
