### ISSUE TITLE
generated nexus.d.ts not recognised by zeit now 

### ISSUE THREAD

**Issue by iherger** [graphql-nexus/nexus-plugin-prisma#382]
Changing the type generation output to 
```typescript
  outputs: {
    typegen: join(__dirname, '/generated/nexus.d.ts'),
    schema: join(__dirname, '/schema.graphql'),
  },
```
as suggested in the nexus-prisma example: https://github.com/prisma/nexus-prisma/blob/ea06caa37337cc93679dba459ac57b0ffb0fdcfd/example/src/index.ts#L22 leads to the following error when deploying to zeit now:
```
Unable to require `.d.ts` file.
This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or another executable extension and loader (attached before `ts-node`) available alongside `nexus.d.ts`.
```

**Comment by jasonkuhrt** [comment]
You shouldn’t hav to require the nexus.d.ts file. TypeScript should pick that up automatically I think. Is it zeit or your code doing the require?

**Comment by iherger** [comment]
I am not requiring the `nexus.d.ts` file anywhere, but zeit now seems to do that...

**Comment by jasonkuhrt** [comment]
@iherger thanks for confirming. I don't know much about zeit (yet). Could it be that there is a way to configure it to not do this? What you're encountering is a pretty general problem and seems outside the scope of `nexus-prisma`. That said, we want to integrate well with other tools. I just need to understand the boundaries of integrating with zeit better.

**Comment by jasonkuhrt** [comment]
@iherger I think we can close this. This pattern is no longer suggested anywhere (or won't be for long once things get updated).
