### ISSUE TITLE
[Prisma 1] Modify InputObjectType does not invalidate cache?

### ISSUE THREAD

**Issue by trungtin** [graphql-nexus/nexus-plugin-prisma#387]
The code:
```
const CommunityCreateInput = prismaInputObjectType({
  name: 'CommunityCreateInput',
  definition: t => {
    t.prismaFields([
      ...remove_some_fileds
    ])
    t.field('added_field', {
      type: 'String',
      required: true,
    })
  },
})

const Mutation = prismaObjectType({
  name: 'Mutation',
  definition(t) {
    t.prismaFields(['createCommunity'])

    /** == DOESN'T WORK == */
    t.modify('createCommunity', {
      resolve: () => { // code }
    })

    /** == WORK == */  // recreate whole field work
    t.field('createCommunity', {
      args: {
        data: arg({ type: 'CommunityCreateInput', required: true }),
      },
      type: 'Community',
      nullable: false,
      resolve: () => { // code }
    })
  },
})
```

As the code show, if we modify the argument InputType fields, then modify the mutation field doesn't work. The error is throw from BatchedGraphQLClient.js file from the http-link-dataloader, somehow this still has the cached schema

**Comment by Weakky** [comment]
I'm not myself familiar with `t.modify()`, but I'm pretty sure it's not meant to do what you want to achieve. The doc says `modifies a field added via an interface`.

With Prisma 1, instead, use `t.prismaType`.

```
t.field('createCommunity', {
  ...t.prismaType.createCommunity,
  resolve: () => { // code }
})
```

More on documentation here: https://nexus.js.org/docs/database-access-with-prisma#tprismatype

**Comment by trungtin** [comment]
thank @Weakky :D
And one more thing, this is what generated from nexus-prisma-generate:
```
createCommunity: {
    type: 'Community'
    args: Record<MutationCreateCommunityArgs, core.NexusArgDef<string>>
    description: string
    list: undefined
    nullable: false
    resolve: (
      root: core.RootValue<"Mutation">,
      args: { data: CommunityCreateInput }  ,
      context: core.GetGen<"context">,
      info?: GraphQLResolveInfo
    ) => Promise<prisma.Community> | prisma.Community
  }
```
it should be
```
args: Record<MutationCreateCommunityArgs, core.NexusArgDef<'CommunityCreateInput'>>
```
for your code snippet to work, maybe incompatible with nexus version? or nexus-prisma-generate? Here is the line of code which generated it:
https://github.com/prisma/nexus-prisma/blob/24cd7d2c0a462deb2231178151ad6a23d8f802c0/packages/nexus-prisma-generate/src/index.ts#L288-L291
