### ISSUE TITLE
Mutation naming convention/Outdated Prisma doc examples.

### ISSUE THREAD

**Issue by ghost** [graphql-nexus/nexus-plugin-prisma#388]
Which naming convention do you prefer for mutations `create/update/deleteOneSomething` or `create/update/deleteSomething` ?

Nexus-prisma currently uses the former but the examples here https://nexus.js.org/docs/database-access-with-prisma-v2 and https://nexus.js.org/docs/database-access-with-prisma are using the latter.

**Comment by Weakky** [comment]
Hey @AWey95 👋,

I personally prefer `create/update/deleteSomething`, that's how it used to be on Prisma 1.
We already updated `Query.findOneSomething` and `Query.findManySomething` to `Query.something` & `Query.somethings`. It'd probably feel better to follow the same pattern. cc @jasonkuhrt

**Comment by jasonkuhrt** [comment]
@Weakky For this issue, IIUC, we've resolved it by updating the nexus docs (we just have to publish the changes).

However I think we could improve the default naming strategy. Is there an open issue tracking that somewhere? Don't think so.

**Comment by Weakky** [comment]
Well, this issue actually treats both issues. According to the title, yes it's solved and we just need to publish the changes.

Let me create another issue for the naming strategy issues

**Comment by jasonkuhrt** [comment]
This issue is resolved, we just need the new nexus docs to be published which is currently out of my control.
