### ISSUE TITLE
Filtering by Float does not work if model contains DateTime field (Prisma2)

### ISSUE THREAD

**Issue by nhuesmann** [graphql-nexus/nexus-plugin-prisma#391]
### Steps to Reproduce Issue

1. Run `prisma2 init`, choosing `SQLite`, `TypeScript`, and `GraphQL boilerplate`.
2. Update `User` model to include a Float as well as the standard `createdAt` and `updatedAt` fields:
```js
model User {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  email     String   @unique
  name      String?
  rating    Float
  posts     Post[]
}
```
3. Run `lift` migration and generate new `photon` client
4. Expose the `findManyUser` query on the `Query` object in `index.js`, and enable filtering and ordering.
```js
const Query = objectType({
  name: 'Query',
  definition(t) {
    t.crud.findManyUser({
      filtering: true,
      ordering: true
    });
    ...
});
```
5. Start server
6. Try running the following query in playground:
```js
query {
  findManyUser(where: { rating: { gte: 0.2 } }) {
    id
  }
}
```
7. Get the following error:
```
Error:
Invalid `photon.users.findMany()` invocation in /Users/nathanhuesmann/Code/experimental/prisma2-nexus-bug/node_modules/graphql-extensions/src/index.ts:155:61

Argument gte: Got invalid value
{
<full ast tree included in attached error doc>
}
on photon.findManyUser. Provided Json, expected Float.

    at Document.validate (/Users/nathanhuesmann/Code/experimental/prisma2-nexus-bug/node_modules/@generated/photon/runtime/index.js:2792:23)
    at UserClient.get _document [as _document] (/Users/nathanhuesmann/Code/experimental/prisma2-nexus-bug/node_modules/@generated/photon/index.js:205:22)
    at UserClient.then (/Users/nathanhuesmann/Code/experimental/prisma2-nexus-bug/node_modules/@generated/photon/index.js:226:63)
    at whenResultIsFinished (/Users/nathanhuesmann/Code/experimental/prisma2-nexus-bug/node_modules/graphql-extensions/src/index.ts:171:12)
    at field.resolve (/Users/nathanhuesmann/Code/experimental/prisma2-nexus-bug/node_modules/graphql-extensions/src/index.ts:156:7)
    at resolveFieldValueOrError (/Users/nathanhuesmann/Code/experimental/prisma2-nexus-bug/node_modules/graphql/execution/execute.js:486:18)
    at resolveField (/Users/nathanhuesmann/Code/experimental/prisma2-nexus-bug/node_modules/graphql/execution/execute.js:453:16)
    at executeFields (/Users/nathanhuesmann/Code/experimental/prisma2-nexus-bug/node_modules/graphql/execution/execute.js:294:18)
    at executeOperation (/Users/nathanhuesmann/Code/experimental/prisma2-nexus-bug/node_modules/graphql/execution/execute.js:238:122)
    at executeImpl (/Users/nathanhuesmann/Code/experimental/prisma2-nexus-bug/node_modules/graphql/execution/execute.js:85:14)
```

### Temporary Workaround

- Remove the `createdAt` and `updatedAt` fields

### Additional

- `prisma2@2.0.0-preview-8, binary version: 6146c81a771bef78248317cef9e37fc00863dc08` (installed globally)
- Full error with ast tree can be seen here: [nexus-bug.txt](https://github.com/prisma/nexus/files/3543075/nexus-bug.txt)

- This was super challenging to track down! 

### Package.json (for library versions)
```json
{
  "name": "prisma2-nexus-bug",
  "scripts": {
    "start": "ts-node-dev --no-notify --respawn --transpileOnly ./src",
    "seed": "ts-node prisma/seed.ts",
    "postinstall": "prisma2 generate"
  },
  "dependencies": {
    "@prisma/nexus": "^0.0.1",
    "graphql-yoga": "^1.18.3",
    "nexus": "0.12.0-beta.7"
  },
  "devDependencies": {
    "@types/node": "12.7.2",
    "ts-node": "^8.3.0",
    "ts-node-dev": "1.0.0-pre.42",
    "typescript": "3.5.3"
  }
}
```

**Comment by jasonkuhrt** [comment]
Hey @nhuesmann I just updated the example with an attempt at reproducing but could not. 8e7410bc2fe30cbe1212605ac8b912006fb98d24. Could you update your deps and generally diff against the example? This issue might have already been fixed.

**Comment by jasonkuhrt** [comment]
One thing that looks suspect to me is `findManyUser` should be `users`.

**Comment by nhuesmann** [comment]
@jasonkuhrt I'm fully updated. Also, I had `findManyUser` because I was using `@prisma/nexus`. As advised, I moved to `nexus` and have updated the call to be `users`. I think I found out what was going on: In my own project, the `rating` field was **optional** (type `Float?`). For some reason, even after migrations and generating `photon` and a new `schema.graphql` file, the schema was still showing that I could run a `gte` query against `rating`. When I did, I was getting those errors. I had to:
1. Fully wipe all data
2. Make the `rating` field required
3. Try the query again after creating a user

It worked fine, I was able to filter by a `Float` field.

I did however find an issue as a byproduct. If a `DateTime` field is added to an existing model that did not previously have a `DateTime` field, querying that model throws errors (any query). Here's how to reproduce:

1. Run `prisma2` init, ensuring lift migrations have been run and `photon` client is generated.
2. Run migration and generate `photon` client
3. Expose the `t.crud.users` query on the `Query` object, ensuring that `filtering`, `ordering`, and `pagination` are all `true`.
4. Start the server
5. Create a user
6. Run the following query:
```
query {
  users {
    id
    name
  }
}
```
8. Your user should be found.
9. Shut down server.
10. Add the following to the `User` model in `schema.prisma`:
```
model User {
  id        String   @default(cuid()) @id
  👉 updatedAt DateTime @updatedAt 👈
  email     String   @unique
  name      String?
  posts     Post[]
}
```
11. Create and run migration, generate new `photon` client.
12. Start the server
13. Run the EXACT same query as above
14. Error:
```
Oops, an unknown error occured! This is on us, you did nothing wrong.
It occured in the `photon.()` invocation in /Users/nathanhuesmann/Code/experimental/prisma-filter-bug/node_modules/graphql-extensions/src/index.ts:155:61

Reason: Could not parse stored DateTime string: 1970-01-01 00:00:00: ParseError(Invalid) in src/libcore/result.rs:999:5
```

I'm assuming Prisma2 is trying to parse the newly added `updatedAt` field for an existing record that does not have a value for that field. It makes sense, however this is a bug because the migration went through successfully and without warning, then bricked my app.

**Comment by divyenduz** [comment]
@nhuesmann Your last comment looks like a Photon issue (that might be dependent on the data stored in the database via nexus or `updateAt` or something else). Can you please try to reproduce it in isolation (without nexus for example) and if you are able to, please post an issue here with a minimal repro: https://github.com/prisma/photonjs/issues/new

Thank you

**Comment by nhuesmann** [comment]
Closing this issue as it was fixed in a later version of Photon.
