### ISSUE TITLE
usage of prismaObjectType from 'nexus-prisma' produces an anoying warning in vscode

### ISSUE THREAD

**Issue by kanso-git** [graphql-nexus/nexus-plugin-prisma#397]
dear all,

I am using prismaObjectType from 'nexus-prisma'
`import { prismaObjectType } from 'nexus-prisma'`

But this usage produces the following warning:
`Expression produces a union type that is too complex to represent.`

I have tried many things to fix this warning but without success.

 Any help will be appreciated.

**Comment by raheelriax** [comment]
Facing this exact issue

**Comment by raheelriax** [comment]
Downgrade your typescript version to 3.4. It'll do the fix. It did for me
