### ISSUE TITLE
CRUD only for instance owned by used

### ISSUE THREAD

**Issue by cyril94440** [graphql-nexus/nexus-plugin-prisma#399]
Hi there,

Awesome library !!

Is there a way to simply modify the default resolver keeping all the filtering, paging, sorting features but limiting results to instances owned by the authenticated users ? 

That would be only applying the same logic but filtering before resolving with idUser = ctx.idUser

It would be great instead of re-writing everything.

Thank you very much for your help!

**Comment by cyril94440** [comment]
did that! seems to be working but not sure it's the best way!

Also I have no idea how to do the same with Connections!

(sorry I don't know how to correctly format the code)
```
export const Query = prismaObjectType({
	name: "Query",
	definition(t) {
		t.field("jobs", {
			...t.prismaType.jobs,
			args: t.prismaType.jobs.args,
			resolve: async (root, args, ctx) => {
				if (!ctx.idUser) {
					throw new Error(
						"No user ID, should not be possible to come here"
					);
				}
				args.where = { ...args.where, user: { id: ctx.idUser } };
				return await ctx.prisma.jobs(args);
			}
		});
	}
});
```

**Comment by Weakky** [comment]
Hey 👋,

That's indeed the way to do it. No need to precise `args: t.prismaType.jobs.args`.

```ts
export const Query = prismaObjectType({
	name: "Query",
	definition(t) {
		t.field("jobs", {
			...t.prismaType.jobs,
			resolve: async (root, args, ctx) => {
				if (!ctx.idUser) {
					throw new Error(
						"No user ID, should not be possible to come here"
					);
				}
				return await ctx.prisma.jobs({
				  ...args.where,
  				  user: { id: ctx.idUser }
				});
			}
		});
	}
});
```
