### ISSUE TITLE
Duplicate identifiers in @generated/nexus-prisma/index.d.ts

### ISSUE THREAD

**Issue by deadcoder0904** [graphql-nexus/nexus-plugin-prisma#411]
I did the following in `Query`

```js
t.crud.tempBlogs({
  alias: 'tempBlogs',
})
```

And in `@generated/nexus-prisma/index.d.ts`, a duplicate identifier warning was generated:

```ts
interface NexusPrismaTypes {
  Query: {
    tempblogs: 'TempBlogs'
    tempblogs: 'TempBlogs'
  }
}
```

I did it wrong but probably think that this shouldn't happen anyways.

**Comment by iherger** [comment]
You should use the _singular_ form for your model name, see: https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md#naming-models

So, try renaming your model to `TempBlog` and everything should work fine.

**Comment by deadcoder0904** [comment]
Okay now it works, however, it does show 2 properties now ⸺

```ts
interface NexusPrismaTypes {
  Query: {
    tempblogs: 'TempBlog'
    tempblog: 'TempBlog'
  }
}
```

Is this normal?

**Comment by iherger** [comment]
Yes, that's correct.

**Comment by deadcoder0904** [comment]
Cool thanks :)

**Comment by schrobak** [comment]
I have this `schema.prisma` model definition

```graphql
model Media {
  id String @id
}

model Audio {
  id String @id
}
```

After generating the nexus prisma types I end up with 
```ts
interface NexusPrismaTypes {
  Query: {
    media: 'Media'
    media: 'Media'
    audio: 'Audio'
    audio: 'Audio'
  }
}
```

It looks `nexus-prisma` does not handle correctly those words. When I change the `Media` to `Medio` it generates types correctly.

Any ideas why?
