### ISSUE TITLE
Non-nullable array fields

### ISSUE THREAD

**Issue by keat01** [graphql-nexus/nexus-plugin-prisma#422]
In the example project, there is:

**example/prisma/schema.prisma**
```
model Blog {
  id        Int      @id
  ...
  authors   Author[]
}
```

**example/src/types/Blog.ts**

```
export const Blog = objectType({
  name: 'Blog',
  definition(t) {
    t.model.id()
    ...
    t.model.authors()
  },
})
```

**example/schema.graphql (generated)**
```
...

authors(after: String, before: String, first: Int, last: Int, skip: Int): [Author!]
```

Please, is there a way to generate a non-nullable result: `[Author!]!` instead of nullable `[Author!]`? 

Based on [Prisma2 documentation](https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md) (section Type Modifiers), the list is non nullable, unless suffixed with `?`.  In the [Nexus documentation](https://nexus.js.org/docs/getting-started) it is stated: 

> all fields are "non-null" unless otherwise specified with a nullable option set to true 

So I think the default should be `[Author!]!`. But even if it is not, I haven't found a way to change this behavior, for example in the params of  `t.model.authors(...)`. Is it possible please?

**Comment by Weakky** [comment]
This was a nexus-prisma bug and has been fixed by https://github.com/prisma-labs/nexus-prisma/pull/452, closing now 🙏
