### ISSUE TITLE
No exported members prismaObjectType and makePrismaSchema

### ISSUE THREAD

**Issue by mateja176** [graphql-nexus/nexus-plugin-prisma#431]
```
Module '"../node_modules/nexus-prisma/dist"' has no exported member 'prismaObjectType'.
Module '"../node_modules/nexus-prisma/dist"' has no exported member 'makePrismaSchema'.
```

Further confirmed by 

```
const Query = prismaObjectType({
              ^
TypeError: nexus_prisma_2.prismaObjectType is not a function

```

Package version:

```
    "nexus-prisma": "^0.4.2",

```

**Comment by mateja176** [comment]
Solved by installing an older version, namely `yarn add nexus-prisma@^0.3`.
Version `0.4.0` introduced breaking changes and the docs became stale, including:
https://nexus.js.org/docs/database-access-with-prisma#examples
https://www.prisma.io/docs/get-started/03-build-graphql-servers-with-prisma-TYPESCRIPT-t201/

**Comment by Weakky** [comment]
Hey 👋,

We're about to provide a migration doc from O.3x to 0.4x. Note that 0.4x is using prisma2 and no longer compatible with prisma1.

You can find the release note here: https://github.com/prisma-labs/nexus-prisma/releases/tag/v0.4.1

Here's a gist of the announcement we did on our public slack:


> Second up is our announcement that starting with nexus-prisma@0.4 support for Prisma 1 will be dropped. For those following the repo you’ve probably already sensed this coming, but we want to make this official and clear so that you can plan accordingly sooner than later. All current and future Prisma 1 specific GitHub issues have been/will be marked with a note/prisma1 label. You can expect these issues to generally not be worked on by the core team. In the future we will probably also close these issues as note/wontfix to bring further clarity. Finally, expect a migration doc soon. We realize early adopters who invested heavily into nexus-prisma@0.3 may feel left out here. Please do chime in with any feedback you have in our tracking issue for this change at https://github.com/prisma/nexus-prisma/issues/378.

**Comment by jjangga0214** [comment]
@Weakky 

> Note that 0.4x is using prisma2 and no longer compatible with prisma2.

It should mean

> Note that 0.4x is using prisma2 and no longer compatible with prisma **1**.

?

**Comment by Weakky** [comment]
My bad @jjangga0214, yes you're right 🤦‍♂😄

**Comment by johhansantana** [comment]
which version should I use for prisma1? I'm trying to create a new project but prisma2 is still not production ready.
