### ISSUE TITLE
Prisma2: Modify required model fields to make them optional/nullable

### ISSUE THREAD

**Issue by jondewoo** [graphql-nexus/nexus-plugin-prisma#438]
Modifying a required model field to make it optional/nullable does not seem possible :

```javascript
t.modify('email', {
    type: 'String',
    nullable: true,
    resolve: () => null, // Type '() => null' is not assignable to type 'FieldResolver<"User", "email">'. Type 'null' is not assignable to type 'MaybePromise<string>'.ts(2322)
});
```

Above, the nullable property is ignored as the field is declared as required in the .prisma model file. The goal is to be able to hide a field under certain conditions, for example if the caller does not have permission to view the users' email addresses stored in the database.

**Comment by jderrough** [comment]
Modifying a required model field to make it optional/nullable does not seem possible :

```
t.modify('email', {
    type: 'String',
    nullable: true,
    resolve: () => null, // Type '() => null' is not assignable to type 'FieldResolver<"User", "email">'. Type 'null' is not assignable to type 'MaybePromise<string>'.ts(2322)
});
```

Above, the nullable property is ignored as the field is declared as required in the .prisma model file. The goal is to be able to hide a field under certain conditions, for example if the caller does not have permission to view the users' email addresses stored in the database.

**Comment by jondewoo** [comment]
I'm also having trouble using `t.modify()` altogether. Here is a simple test case:

```javascript
const Query = queryType({
    definition(t) {
        t.crud.users();
        t.modify('users', {
            resolve: () => {
                console.log('foo');
                return [];
            },
        });
    },
});
```

The users query returns the actual users in the database and resolve is never called. A usage example of `t.modify()` would be nice.

**Comment by jondewoo** [comment]
Reading from the [documentation](https://nexus.js.org/docs/api-interfacetype) and the code of [buildObjectType](https://github.com/prisma-labs/nexus/blob/develop/src/builder.ts#L721) in the `nexus` module, `t.modify()` is only intended to replace the `description` string and the `resolve` function of an implemented interface field. For example (not tested):

```javascript
const Node = interfaceType({
  name: "Node",
  definition(t) {
    t.id("id", { description: "GUID for a resource" });
  },
});

const User = objectType({
  name: "User",
  definition(t) {
    t.implements("Node");

    t.modify("id", {
        description: "UUIDV4 for a resource",
        resolve: () => uuidv4()
    });
  },
});
```

Shouldn't the compiler tell me that trying to modify a field not originating from an interface isn't supported? Maybe it would make more sense to be able to modify all kinds fields.

This looks like two different issues, both more related to the `nexus` module than `nexus-prisma`:
- make it possible to modify all fields
- make it possible to modify fields to make them nullable or non-nullable

I'll probably get the ball rolling tomorrow on these.

**Comment by jondewoo** [comment]
Found a workaround by using `extendType`:

```javascript
const UserDef = objectType({
    name: 'User',
    definition(t) {
        t.model.id();
        t.model.email();
        t.model.name();
    },
});

// elsewhere...

const UserImpl = extendType({
    type: 'User',
    definition(t) {
        t.field('email', {
            type: 'String',
            nullable: true,
            resolve: (root) => {
                if (notAdmin) {
                    return null;
                }

                return root.email;
            },
        });
    },
});
```

**Comment by jderrough** [comment]
Reopening the issue as that point still stands:

> Shouldn't the compiler tell me that trying to modify a field not originating from an interface isn't supported?
