### ISSUE TITLE
Caching directives from apollo in schema

### ISSUE THREAD

**Issue by akoufa** [graphql-nexus/nexus-plugin-prisma#439]
Hey I am trying to introduce `@cacheControl` from https://www.apollographql.com/docs/apollo-server/performance/caching/ to provide HTTP caching headers in the response and unfortunately I cannot find a way to add them via **nexus-prisma**. It is only possible when using GraphQL Schema definition through SDL but I would like to define it via code-first GraphQL. Is it possible to add this functionality to nexus-prisma ?

**Comment by iherger** [comment]
You can add cache hints dynamically to your resolvers (not only statically in your schema), see https://www.apollographql.com/docs/apollo-server/performance/caching/#adding-cache-hints-dynamically-in-your-resolvers

**Comment by akoufa** [comment]
Hello @iherger. I know that I can already add cache hints dynamically in the resolvers but I don't want to add in every resolver method, extra static caching code when I could do that via a directive. That's why I opened this issue to request the possibility to add custom directives using nexus-prisma.

**Comment by iherger** [comment]
@akoufatzis, sorry, then I misunderstood your question. Your question seems to have been discussed before in https://github.com/prisma-labs/nexus/issues/53 and it seems to be in the pipeline.

**Comment by akoufa** [comment]
Ok then I will close this issue and follow the one you mentioned. Thank you.

**Comment by alexandrduduka** [comment]
Hey, we are hitting the same problem, trying to define cacheControls on the specific queries, but have no luck.

When using the constructions like `t.model.order` on some of the object types, there is no way to specify maxAge for the nested fields. Let's say we have a construction like order -> customer -> addresses -> id, in this case even if we specify cache hint on the order subfields will have defaultMaxAge=0, and the request never gets cached. We have been trying different workarounds but did not manage to get it running. 

Is there some known way to deal with this issue? I can't believe the whole code-first community runs without using caching :) 

@akoufa, could you share your findings?
@iherger, I see that the discussion you mentioned leads to this hanging issue https://github.com/apollographql/apollo-server/issues/3589, is there some known way to provide cache hints for nested fields without rewriting everything to custom types and resolves and utilizing all the Prisma goodies?

Thanks a lot in advance!
