### ISSUE TITLE
Typescript compilation fails /  Cannot find module '@prisma/photon'

### ISSUE THREAD

**Issue by iherger** [graphql-nexus/nexus-plugin-prisma#445]
For version `0.5.0-next.3` (and also `0.5.0-next.1`), the typescript compilation `tsc` fails with the following error message:
```
node_modules/nexus-prisma/dist/dmmf/transformer.d.ts:2:22 - error TS2307: Cannot find module '@prisma/photon'.

2 import { DMMF } from '@prisma/photon';
                       ~~~~~~~~~~~~~~~~

node_modules/nexus-prisma/dist/dmmf/utils.d.ts:1:25 - error TS2307: Cannot find module '@prisma/photon'.

1 import * as Photon from '@prisma/photon';
                          ~~~~~~~~~~~~~~~~
```
Prisma2 version: `prisma2@2.0.0-alpha.226`

**Comment by iherger** [comment]
This can be fixed by adding `@prisma/photon` as a _devDependency_ in my project (which is not ideal, I guess). Or by moving the `@prisma/photon` in `nexus-prisma` from a _devDependency_ to a normal _dependency_ (which fixes is for everyone).

**Comment by jasonkuhrt** [comment]
> moving the @prisma/photon in nexus-prisma from a devDependency to a normal dependency

👍 Yep this is what we'll do CC @Weakky

**Comment by jasonkuhrt** [comment]
I wonder how we could setup integration / CI tests to catch this kind of error.

**Comment by kripod** [comment]
I've just encountered the following issue when using `nexus-prisma` in a monorepo:

![image](https://user-images.githubusercontent.com/14854048/69061057-c6431780-0a18-11ea-87d5-7f49cc6f5605.png)

The source code is available from [kripod/exigo](https://github.com/kripod/exigo), and the issue can be reproduced as follows:

1. Run `yarn` from the root directory, which executes `postinstall`, invoking the server's `generate` script _(which is basically `prisma2 generate && prisma2 lift up --create-db && ts-node --transpile-only src/graphql/schema`)_
2. Run `yarn type-check` from the root of the server project

**Comment by iherger** [comment]
I have the same issue.

**Comment by yangga** [comment]
same here

**Comment by kripod** [comment]
As a temporary measure, I've appended the following to my `tsconfig.json`:

```jsonc
{
  "compilerOptions": {
    "skipLibCheck": true // TODO: Remove when nexus-prisma gets fixed
  }
  // ...
}

```

**Comment by yangga** [comment]
```
yarn add @prisma/photon@0.2.152
```

above works for me

**Comment by kripod** [comment]
If I understand correctly, `@prisma/photon` will replace `@generated/photon` as a facade, making the latter obsolete. Currently, `@prisma/photon` is only being used for its types with no actual functionality, so it’s safe to ignore it until it gets added as a regular dependency.
