### ISSUE TITLE
Feature Request- Debug mode for Photon/Nexus

### ISSUE THREAD

**Issue by CaptainChemist** [graphql-nexus/nexus-plugin-prisma#448]
It was brought up in the Prisma2 Preview slack channel that it would be useful to have a debug feature between photon + nexus. I'll go through the use case now. Let's say we have  the following models:

````
model Joke {
  id      String @default(cuid()) @id
  author  Author
  content String @unique
}

model Author {
  id    String @default(cuid()) @id
  name  String
  jokes Joke[]
}
````

If we have a resolver that is the following, how can we easily tell whether the return type matches what we get back from the photon authors call? 

````
t.list.field('getJokeByAuthor', {
    type: 'Joke',
    args: {
        name: stringArg(),
    },
    resolve: (_, {name}, ctx) => {
        return ctx.photon.authors.findMany({
            where: {
                name,
            },
            select: {
                jokes: true,
            },
        });
    },
});
````

We could add an async/await like this and then add a console.log so we could output the result and do a sanity check of whether it matches the return type of `Joke` before returning it, but it might be cool if there was a debug mode so that we could always output the return from photon calls so we wouldn't have to actually add the async/await and console.logs only to remove them after we figure out what is going on with our resolver.

````
t.list.field('getJokeByAuthor', {
    type: 'Joke',
    args: {
        name: stringArg(),
    },
    resolve: async (_, {name}, ctx) => {
        const result =  await ctx.photon.authors.findMany({
            where: {
                name,
            },
            select: {
                jokes: true,
            },
        });
        console.log(result);
        return result;
    },
});
````

The problem that AK2 was running into on the slack channel was that they were getting a `"Cannot return null for non-nullable field Joke.id."` error but couldn't figure out why.

**Comment by jasonkuhrt** [comment]
> but it might be cool if there was a debug mode so that we could always output the return from photon calls so we wouldn't have to actually add the async/await and console.logs only to remove them after we figure out what is going on with our resolver.

There are various ways to achieve this I guess. You could avoid `await` but chaining a tap like:
```ts
const tap = <T>(f: (x: T) => void) => (x: T): T => {
  f(x)
  return x
}
```
```ts
.then(tap(console.log)))
```

But to get something standard and app wide, as you say a mode, I think middleware could help with that. Keep an eye on https://github.com/prisma-labs/nexus/issues/98 which should be closing soon. Something like as follows would be then possible:

```ts
export const loggerPlugin = plugin({
  name: "Logger",
  description: "Log resolver responses",
  onCreateFieldResolver: () => {
    return async (root, args, ctx, info, next) => {
      const result = await next(root, args, ctx, info)
      console.log(result)
      return result
    };
  },
});
```

Would that address your use-case? Closing for now but let me know if you think plugins wouldn't be enough.

**Comment by jasonkuhrt** [comment]
@CaptainChemist Nexus will include, at least initially, a series of bundled plugins users can opt into using. Maybe a middleware logger should be among those plugins. If that would interest you, open an issue on Nexus repo to share your use-case 👍
