### ISSUE TITLE
Allow orderBy with nested attributes

### ISSUE THREAD

**Issue by cimchd** [graphql-nexus/nexus-plugin-prisma#458]
I want to order a table by a nested attribute. I tried something like this:

```
query {
  posts (orderBy: { author: { name : desc } } ) {
    content
    author {
      name
    }
  }
}
```
But the result was that author is not available there. I checked the generated oderby-input-type and there were only the scalar attributes of the post model available, the related models are missing.

Is it possible to extend the generated input types ...OrderByInput to include the related models?

**Comment by Weakky** [comment]
Hey @cimchd 👋,

This is a Prisma core limitation at the moment. Once the core supports it, so will nexus-prisma.
Please create an issue on https://github.com/prisma/prisma2 if there isn't one already 🙏

**Comment by cimchd** [comment]
Ok, thanks. I just created a similiar issue in the photonjs repo: https://github.com/prisma/photonjs/issues/249

**Comment by jasonkuhrt** [comment]
@Weakky should we keep this open to track our needing to do it once Photon unblocks us? We could label it `needs/upstream` or something.
