### ISSUE TITLE
t.prismaFields(['*']) in prismaObjectType

### ISSUE THREAD

**Issue by tony-go** [graphql-nexus/nexus-plugin-prisma#476]
Hi Guys :) ✋ 

I recently followed this blog post aiming to build an new API : https://www.prisma.io/blog/using-graphql-nexus-with-a-database-pmyl3660ncst

(=> https://github.com/prisma/prisma-examples/blob/master/typescript/graphql-crud/src/index.ts)

I had some troubles to use : 

```typescript
import { prismaObjectType } from 'nexus-prisma'

const User = prismaObjectType({
  name: 'User',
  definition(t) {
    t.prismaFields(['*'])
  },
```
I use an old version to make the magic happens, but the API seems to be changed :) 

Do you have something equal to `t.prismaFields(['*'])` in the new API ?

Awsome job btw :)

**Comment by Weakky** [comment]
Hey @tony-go, this is currently not supported in the new API.
Feel free to chime in this issue #299 to up-vote it and/or share your use-case 🙏
Closing now as duplicate
