### ISSUE TITLE
Tailor DateTime scalar filter to the domain of time

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/nexus-plugin-prisma#484]
Currently we have:

```gql
input DateTimeFilter {
  equals: DateTime
  gt: DateTime
  gte: DateTime
  in: [DateTime!]
  lt: DateTime
  lte: DateTime
  not: DateTime
  notIn: [DateTime!]
}
```

This just an `IntFilter` using `DateTime` scalar type. I think we should filter tailored to the domain of time.

**Comment by jasonkuhrt** [comment]
May be desirable to push upstream into Photon.

Proposal:

```gql
input DateTimeFilter {
  at: DateTime
  before: DateTime
  beforeOrAt: DateTime
  after: DateTime
  afterOrAt: DateTime
  within: [DateTime!]! # domain-friendly short hand for specifying a before & after
  notWithin: [DateTime!]!
}
```

Loses some power but for the domain of time seems fine and now its simpler + clearer.

CC @Weakky do you think this is a better default API for GQL clients?

I'm not sure, tbh

**Comment by Weakky** [comment]
While I like it, I'm wondering whether the change is worth the lack of consistency with all other filter types (String/Int/Float/BooleanFilter)

**Comment by jasonkuhrt** [comment]
Feels like something that should be possible via customization/naming strategy. We can reference this issue as a use-case/example when we tackle that. Not only does my example show name strategy change, but also actual field changes (some ones added, some ones removed).
