### ISSUE TITLE
Can't get correct model types string

### ISSUE THREAD

**Issue by outerlook** [graphql-nexus/nexus-plugin-prisma#493]
Hi! I will try to be the most short as possible. Please could you warn me if it lacks information?

The error:
![image](https://user-images.githubusercontent.com/12937160/66944761-33cbe480-f024-11e9-9447-563c9c892cb4.png)
Only the initial scalars are being pulled, although there are more in my datamodel.

for example:
![image](https://user-images.githubusercontent.com/12937160/66944969-9ae99900-f024-11e9-9a92-34d90e9269e6.png)
Does this proof I did generate correctly?

```

//src/index


import { GraphQLServer } from "graphql-yoga";
import { nexusPrismaPlugin } from "nexus-prisma";
import { makeSchema } from "nexus";
import * as allTypes from "./api";
import { join } from "path";
import { permissoes } from "./permissoes/index";
import { Photon } from "@generated/photon";

const photon = new Photon({ debug: true });

const nexusPrismaTypes = nexusPrismaPlugin({
  types: allTypes,
});

const schema = makeSchema({
  types: [allTypes, nexusPrismaTypes],
  typegenAutoConfig: {
    debug: true,
    sources: [
      {
        source: "@generated/photon",
        alias: "photon"
      },
      {
        source: join(__dirname, "types.ts"),
        alias: "ctx"
      }
    ],
    backingTypeMap: {
      Date: "Date",
      Upload: "Upload"
    },
    contextType: "ctx.Context"
  },
  outputs: {
    schema: join(__dirname, "./schema.graphql")
  }
});

export const server = new GraphQLServer({
  schema,
  // middlewares: [permissoes],
  context: request => ({
    ...request,
    photon
  })
});

server.start(() => console.log(`Server is running on http://localhost:4000`));
```

It appears to be no error when starting....
```
[INFO] 14:56:22 Restarting: manual restart from user
Using ts-node version 8.3.0, typescript version 3.4.5
Server is running on http://localhost:4000
  getos { platform: 'win32', libssl: undefined } +0ms
GraphQL Nexus: No match for Time in "@generated/photon" using /(?:interface|type|class|enum)\s+(Time)\W/g
GraphQL Nexus: No match for Time in "..\..\..\src\types" using /(?:interface|type|class|enum)\s+(Time)\W/g
```

How can I provide more info? Trying to solve this since yesterday, sorry if I missed something...

**Comment by jasonkuhrt** [comment]
Hey @outerlook, we just released a new version, you can look at docs & repo examples for details. Not sure yet what your issue is. I'm not super familiar with with the `backingTypes` system, and wonder if that could be related to your issue.

**Comment by Weakky** [comment]
I think the reason why your output types are not appearing is that you're not calling the functions of `t.crud.`, you're simply accessing them as properties, which does nothing.

Try the following for all `t.crud`/`t.model` (`estados` is just an example):

```diff
- t.crud.estados
+ t.crud.estados()
```

**Comment by outerlook** [comment]
You're right, I missed that...

But still I can't make it work. It seems to miss the "type" argument.
![image](https://user-images.githubusercontent.com/12937160/67212731-2a12fa00-f3f3-11e9-9b6f-8df6769dc733.png)

```
Error: 
- Missing type CategoriaDeComodidade, did you forget to import a type to the root query or mean CategoriaDeComodidadeOrderByInput?
    at assertNoMissingTypes (C:\projetob\yugi\backend\node_modules\nexus\src\builder.ts:1663:11)
    at Object.makeSchema (C:\projetob\yugi\backend\node_modules\nexus\src\builder.ts:1589:3)
    at Object.<anonymous> (C:\projetob\yugi\backend\src\index.ts:11:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (C:\projetob\yugi\backend\node_modules\source-map-support\source-map-support.js:521:25)
    at Module.m._compile (C:\Users\RAFFAE~2\AppData\Local\Temp\ts-node-dev-hook-5697630631774853.js:57:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at require.extensions.(anonymous function) (C:\Users\RAFFAE~2\AppData\Local\Temp\ts-node-dev-hook-5697630631774853.js:59:14)
    at Object.nodeDevHook [as .ts] (C:\projetob\yugi\backend\node_modules\ts-node-dev\lib\hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

When I look through @generated/photon files, it seems to be correctly generated, with all models I have on datamodel file.

I will try to reproduce the example on examples folder here.

**Comment by outerlook** [comment]
Hi! I realized something I was missing.

Now I must first declare what models will be available on my api declaring it with t.model.MODEL, right? Sorry I didn't realize that before.  I do have many models. Is there any easy way like t.prismaModels(['*']) or something to declare all at once?

without that, every time I want to add a new field to my model, I should update my schema.prisma file and then update also my model on nexus too, is it right?

**Comment by outerlook** [comment]
following #299
