### ISSUE TITLE
t.crud is using camelCase now

### ISSUE THREAD

**Issue by iherger** [graphql-nexus/nexus-plugin-prisma#495]
I have probably missed this, but I just spent rather too much time finding out that the `t.crud` methods are now (version 0.5.0) using camelCase, like photon does, I think.

It could be useful to add this to the migration documentation (or it already is somewhere and I didn't see it).

**Comment by Weakky** [comment]
Sorry about that, this is indeed related to #481, and we missed it when handwriting the changelog. We'll soon have tools to generate it, making sure these are not forgotten. Adding it to the v0.50 changelog now, thanks for reporting 🙏

**Comment by jasonkuhrt** [comment]
Hey @iherger my bad sorry about that.

**Comment by jasonkuhrt** [comment]
Linking: This is an instance motivating https://github.com/prisma-labs/issues/issues/2
