### ISSUE TITLE
Heroku/dokku: start failing with v0.5.0

### ISSUE THREAD

**Issue by iherger** [graphql-nexus/nexus-plugin-prisma#505]
I cloned the Prisma2 GraphQL Auth starter, and deployed to Heroku (with some minor changes, like adding `NEXUS_SHOULD_GENERATE_ARTIFACTS=true` to the build script and fixing a type error [due to `photon.users.findOne` now returning `User|null`]).

Building on Heroku/dokku runs smoothly, but starting the server gives the following error:
```
node dist/server
/app/node_modules/nexus/dist/plugins.js:70
      throw new Error("Plugin " + plugin.config.name + " failed on \"onInstall\" hook:\n\n" + error.stack);
                       ^
Error: Plugin nexus-prisma failed on "onInstall" hook:
Error: Could not find photon package at @generated/photon. Check that you have configured your Photon generator block in schema.prisma correctly and run prisma generate.
```

Reproduction available: https://github.com/iherger/hello-heroku

I get the same error (`Could not find photon package at @generated/photon`) when I try to start my own project.

Not sure if this is a photon or nexus-prisma error, feel free to move the issue to wherever it belongs.

**Comment by iherger** [comment]
It seems that the pruning devDependencies step for dokku/Heroku deployments is now removing `node_modules/@generated/photon` (which was not the case previously).

So, skipping the pruning devDependencies step makes it work again. 

Moving `prisma2` and `@prisma/sdk` to prod dependencies, does not work.

I still wonder what root cause of this is.

**Comment by jasonkuhrt** [comment]
> So, skipping the pruning devDependencies step makes it work again.

How did you do this exactly?

Facades should resolve this issue.

**Comment by iherger** [comment]
> How did you do this exactly?

You can set `NPM_CONFIG_PRODUCTION` to `false` to skip pruning (see https://devcenter.heroku.com/articles/nodejs-support#skip-pruning)

**Comment by jasonkuhrt** [comment]
@iherger thanks, did not know about that feature. Appears to be a Heroku specific env var.
