### ISSUE TITLE
tsc build fails with version 0.5.1

### ISSUE THREAD

**Issue by iherger** [graphql-nexus/nexus-plugin-prisma#524]
When building with `tsc` (`npm -s run clean && npm -s run generate && tsc`), I get the following two errors:
```
../node_modules/@types/nexus-typegen/index.d.ts:7:25 - error TS2307: Cannot find module '@generated/photon'.

7 import * as photon from "@generated/photon"
                          ~~~~~~~~~~~~~~~~~~~

node_modules/@prisma/photon/dist/utils/getDMMF.d.ts:2:32 - error TS2307: Cannot find module '@prisma/sdk'.

2 import { GetDMMFOptions } from '@prisma/sdk';
```

**Comment by iherger** [comment]
OK, the first one was an error or mine.

The second one remains if `@prisma/sdk` is not added as a devDependency in the project.

So closing this in favour of #499

**Comment by jasonkuhrt** [comment]
Hey @iherger, is there something we could have done to make whatever error you made less likely in the first place?

**Comment by iherger** [comment]
@jasonkuhrt , stupid mistake: to upgrade to 0.5.1, I copied your example code
```ts
  outputs: {
    typegen: path.join(
      __dirname,
      '../../node_modules/@types/nexus-typegen/index.d.ts',
    ),
  },
```
to my project. However, in my project, I only need to go up one directory, not two...

**Comment by jasonkuhrt** [comment]
Oh, yeah, for fixing that (dealing with that kind of config), we're building a higher order tool. You've been consistently engaged with our work and I deeply appreciate that. If you're curious, keep your eyes on https://github.com/prisma-labs/pumpkins. Still just a prototype, first few days, who knows.
