### ISSUE TITLE
prisma2@2.0.0-preview016 NexusPrisma type fails with nexus

### ISSUE THREAD

**Issue by CaptainChemist** [graphql-nexus/nexus-plugin-prisma#525]
Using the latest prisma preview 16 client, generates an invalid NexusGenCustomOutputProperties. 

<img width="518" alt="Screen Shot 2019-11-07 at 3 24 56 PM" src="https://user-images.githubusercontent.com/1043257/68429048-f9f98400-0172-11ea-8217-e97b78f5fe19.png">

NexusPrisma type needs to be updated to whatever the new name is.

**Comment by Albert-Gao** [comment]
Interesting, tsc work locally, but not on server even after a successful `prisma2 generate`
I am using `Prisma2 2.0.0preview18.1`

**Comment by Albert-Gao** [comment]
A potential fix: https://github.com/prisma-labs/nexus-prisma/issues/558#issuecomment-564293576

**Comment by jasonkuhrt** [comment]
I wasn’t able to repro in blog example with newest Prisma. Is this still an issue for you?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by macrozone** [comment]
this happens on ci/cd for us, because it only get created into node_modules/@types once that the app runs. but this is not suitable for static code checks like int stages or test stages

**Comment by jasonkuhrt** [comment]
We're now on v22 Prisma preview.

@macrozone feel free to open a new issue.
