### ISSUE TITLE
OR and AND operator doing the same thing with photonjs

### ISSUE THREAD

**Issue by olup** [graphql-nexus/nexus-plugin-prisma#528]
using `primsa2 preview 16.1` and `nexus-prisma 0.5.2` 

So, I've been digging the issues but I can't guarantee that this hasn't been reported elsewhere.

I have a prisma2 schema of a `Page` object, like this one : 
```
model Page {
  id         String  @default(cuid()) @id @unique
  title      String
  slug       String  @unique
  content    String?
}
```

Then I have nexus-prisma Query setup like this :
```
t.crud.pages({ filtering: true });
```

The generated schema is perfect. I do have a `where` operator in the `pages` query, with every fields and various operators.

However, this query : 
```
pages(
    where: {
      title: { contains: $search }, OR : {slug : {contains : $search}}
    }
  ) {
    title
    slug
  }
```
And this one (AND at the place of OR) : 
```
pages(
    where: {
      title: { contains: $search }, AND : {slug : {contains : $search}}
    }
  ) {
    title
    slug
  }
```
gives the same results with various test cases - meaning that they allways behave like a logical AND, only sending back the pages that contains the `$search` string in both the `title` and the `slug` - never the one that have the search string in only one of them.

Is it a bug ? Am I missing something ?

**Comment by iherger** [comment]
I guess you need to do the following:
```
pages(
    where: {
      AND: [ {title: { contains: $search } }, {slug : {contains : $search}} ]
    }
  ) {
    title
    slug
  }
```
or replace the `AND` with `OR`, respectively.

**Comment by olup** [comment]
Yes, actually just saw that from the schema, I missed the `List` type on `AND` and `OR`. Cheers for the help anyway !
