### ISSUE TITLE
Cannot find name 'NexusPrisma'

### ISSUE THREAD

**Issue by chrisdrackett** [graphql-nexus/nexus-plugin-prisma#531]
when running type check on my project I get the following:

```
$ tsc
generated/typegen.ts:29:11 - error TS2304: Cannot find name 'NexusPrisma'.

29     crud: NexusPrisma<TypeName, 'crud'>
             ~~~~~~~~~~~

generated/typegen.ts:30:12 - error TS2304: Cannot find name 'NexusPrisma'.

30     model: NexusPrisma<TypeName, 'model'>
              ~~~~~~~~~~~
```

Should these be imported from somewhere? or am I missing a step?

**Comment by bitmensch** [comment]
Yesterday, I've updated to

```
    "nexus": "^0.12.0-rc.4",
    "nexus-prisma": "^0.5.2",

    "prisma2": "2.0.0-preview016.2",
```

and now I am seeing the same issue.

**Comment by bitmensch** [comment]
I had to run the following to get this solved:

1. Generate Photon client again:

```
prisma2 generate
```

2. Run application so makeSchema(...) gets called again which takes care of updating the typegen.ts file

3. Wait for VSCode to pick up the changes ... this sometimes takes a few seconds (restart may help)

**Comment by ghost** [comment]
I'm experiencing the same issue.`NexusPrisma` type should be coming from `node_modules/@types/nexus-prisma-typegen/index.d.ts`. It is there:
![image](https://user-images.githubusercontent.com/29678037/77295138-acc31c80-6ce5-11ea-829c-67f027c6bc31.png)

But generated `nexus.ts` still can't find it.
![image](https://user-images.githubusercontent.com/29678037/77295212-cebc9f00-6ce5-11ea-82bb-bad92a087173.png)

Any suggestion, please?

**Comment by radicand** [comment]
@cypcz I ran into this because I had added in my `tsconfig.json` a definition for `types: ["node"]`. After removing the `types` key, it compiled fine. If you need your `types` defined there, there is likely a way to make this work too - but that's a pointer in the right direction at least.

**Comment by ghost** [comment]
@radicand thanks, but it didn't work for me. I temporarily fixed it by generating the types again to the folder, where `nexus.ts` lives.

I had to adjust `nexusPrismaPlugin` like this:
```
  plugins: [
    nexusPrismaPlugin({
      // Fixes the Cannot find NexusPrisma issue
      outputs: { typegen: __dirname + '/generated/index.ts' },
    }),
  ],
```

**Comment by dborstelmann** [comment]
Here was the solve for me:

Set "skipLibCheck": true in the compilerOptions property in the tsconfig.json file and run tsc again.

**Comment by mingchuno** [comment]
@radicand try to add `"types": ["nexus-prisma-typegen"]` in your `tsconfig.json`?

**Comment by jasonkuhrt** [comment]
Closing this issue as there’s nothing really actionable for us. It is usually due to tsconfig issues. In the framework we solved this issue completely by managing everything including the tsconfig.

**Comment by bogdancss** [comment]
did anyone manage to get around this issue?

tried adding `outputs: { typegen: path.join(process.cwd(), 'pages', 'api', 'index.ts') }` but getting the same error

**Comment by mohe2015** [comment]
Can you provide more of your code? I currently don't have issues and I just followed the official getting started guide. Like already mentioned it may be because of an invalid tsconfig.

**Comment by bogdancss** [comment]
@mohe2015 [here's](https://github.com/bogdancss/prisma-nexus-apollo-example) a stripped-down repo that has the issue.
It's mainly following [this prisma example](https://github.com/prisma/prisma-examples/tree/master/typescript/graphql-nextjs), with a few changes:

- upgraded to latest @apollo/client and removed all old dependencies, according to [the official migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration)
- installed the nexus-plugin-prisma and replaced the GraphQl Queries and Mutations to use `t.crud....`
- replaced the SQLite database to a Postgres one

The app connects to a Postgres Heroku dataset (used solely for testing - that's why I included the credentials in the repo above).
If you clone the repo, npm i and npm run dev, you should get it up and running locally. It works perfectly fine locally - all mutations and queries work fine.

However, once deployed to Heroku, during build I get the `Cannot find name 'NexusPrisma'` error and deployment stops.

**Comment by jorgenskogas** [comment]
@bogdancss are you using `heroku-prebuild` task when deploying to heroku?

**Comment by bogdancss** [comment]
@jorgenskogas no, here's my scripts block:

```
"scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start -p $PORT",
    "export": "next export",
    "generate": "npm -s run generate:prisma && npm -s run generate:nexus",
    "generate:prisma": "npx prisma generate",
    "generate:nexus": "ts-node --transpile-only -P nexus.tsconfig.json pages/api",
    "migrate": "npm -s run migrate:save && npm -s run migrate:up",
    "migrate:save": "npx prisma migrate save --experimental",
    "migrate:up": "npx prisma migrate up --experimental"
  }

**Comment by mohe2015** [comment]
Can't test because it's really late but the following parts in tsconfig.json may help (honestly I have no idea):
```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "nexus/typescript-language-service"
      }
    ],
    "typeRoots": ["node_modules/@types", "types"],
  },
  "include": ["types.d.ts", "."]
}
```
Also I neither use next.js nor heroku so I can't help more.

**Comment by bogdancss** [comment]
@mohe2015 will give that a shot

**Comment by jorgenskogas** [comment]
@bogdancss this fixed it for me (if you test this locally, clean/delete your node_modules first)
```diff
import { makeSchema } from '@nexus/schema';
import { nexusSchemaPrisma } from 'nexus-plugin-prisma/schema';
import * as types from './types';

export const schema = makeSchema({
	types,
-	plugins: [nexusSchemaPrisma()],
+	plugins: [nexusSchemaPrisma({ outputs: { typegen: __dirname + '/generated/typegen-nexus-plugin-prisma.d.ts' } })],
	outputs: {
		schema: __dirname + '/generated/schema.graphql',
		typegen: __dirname + '/generated/nexus.ts',
	},
	typegenAutoConfig: {
		sources: [
			{
				source: '@prisma/client',
				alias: 'client',
			},
			{
				source: require.resolve('./context'),
				alias: 'Context',
			},
		],
		contextType: 'Context.Context',
	},
});

```

**Comment by bogdancss** [comment]
@jorgenskogas doing that, it builds fine now. However, I am getting this error while trying to call the api:

`Error: EROFS: read-only file system, mkdir '/generated'`

**Comment by bogdancss** [comment]
@jorgenskogas ok, changed that to 
```
outputs: { typegen: path.join(process.cwd(), 'pages', 'api', 'generated', 'typegen-nexus-plugin-prisma.d.ts') }
```
And it seems to be working fine now.

**Comment by oviavo-ts** [comment]
I ended up here after googling the same type error and I would like to mention that when NODE_ENV is set to production, type files are not generated.
In the case where you need to compile typescript on production environment, you need to specify shouldGenerateArtifacts option like below.

``` 
 plugins: [
    nexusSchemaPrisma({
     // Generate typefiles on any occasions 
      shouldGenerateArtifacts : true,
      outputs : {
        typegen: __dirname + '/generated/typegen-nexus-plugin-prisma.d.ts'
      }
    })
  ],
```

**Comment by shkolyar** [comment]
```json
{
  "compilerOptions": {
    // "types": ["node"], // breaks Nexus
    "target": "ESNEXT",
    "module": "commonjs",
```
