### ISSUE TITLE
Subscriptions are not supported yet with `t.prismaFields`

### ISSUE THREAD

**Issue by Weakky** [graphql-nexus/nexus-plugin-prisma#56]
## TODO
- Waiting for https://github.com/prisma/nexus/issues/21 to land
- Resolve subscription types
- Generate proper typings for subscription types

**Comment by williamluke4** [comment]
@Weakky  Anything I can do to help here?

**Comment by Weakky** [comment]
Hey !

PR are always appreciated, feel free to dig into the codebase and create a PR if you feel like so !

As far as I can tell, there are two things to change:

- The generated resolvers needs to support subscriptions (atm, it just throws)
- And generate the correct types in `nexus-prisma-generate`

**Comment by Weakky** [comment]
**Update**: This needs to be rolled out first https://github.com/prisma/nexus/issues/21

**Comment by nevescode** [comment]
@Weakky prisma/nexus#21 is now closed!
More details on PR: https://github.com/prisma/nexus/pull/66
I'm very anxious about subscriptions with nexus-prisma.
I'll try to dig out in the code this weekend to propose a PR. Thanks for the good work!

**Comment by Weakky** [comment]
@nevescode That's amazing! If you need any help, feel free to DM me on the Prisma slack `@weakky` 🙏

**Comment by kolengri** [comment]
Hi any news about this? 😢

**Comment by Weakky** [comment]
Hey everyone,

While we haven't implemented subscriptions yet, it's important to mention that subscriptions **should already work** nonetheless with `nexus` if you implement the resolvers yourself with `subscriptionField()`.

What doesn't work yet are the automatic resolvers when using `t.prismaFields([])`

**Comment by BjoernRave** [comment]
hey, may I ask if you/somebody knows when to expect this feature?

**Comment by mahapo** [comment]
+1

**Comment by sangqle** [comment]
Awesome. Hope as soon as possible.
Have a good day.

**Comment by kolengri** [comment]
So is topic dead? :(

**Comment by mahapo** [comment]
Should be fixed with this https://github.com/prisma/nexus-prisma/releases/tag/v0.3.7

**Comment by pierreyves-lebrun** [comment]
Apologies if I am missing something but isn’t that rather a workaround?

I think subscription via t.prismaFields() syntax is what we are all after.
