### ISSUE TITLE
graphql should not be a peer dep

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/nexus-plugin-prisma#571]
Originated here https://github.com/prisma-labs/nexus-prisma/pull/540#discussion_r362049281

**Comment by ssalbdivad** [comment]
@jasonkuhrt If someone consuming ```nexus-prisma``` didn't have ```graphql``` installed but was using TS, how would ```import { GraphQLResolveInfo } from 'graphql';``` be resolved in the d.ts file? Also ```nexus``` already has ```graphql``` as a peerDependency so effectively ```nexus-prisma``` does as well.

**Comment by jasonkuhrt** [comment]
> @jasonkuhrt If someone consuming nexus-prisma didn't have graphql installed but was using TS, how would import { GraphQLResolveInfo } from 'graphql'; be resolved in the d.ts file?

This would imply:

1. user installed their app deps with `--production`
2. user is running their app with `ts-node` or equivalent

In other words, going to production without a TypeScript build step. Such an approach is not something we optimize for. IIUC its not something the community optimizes for either.

Make sense? Am I missing something?

**Comment by ssalbdivad** [comment]
@jasonkuhrt devDependencies aren't installed recursively the way normal dependencies are. If ```package-a``` has a ```package.json``` like this:

```
{
  "name": "package-a",
  "version": "0.0.1",
  "dependencies": {
    "package-b": "0.0.1"
  }
}
```

and ```package-b``` looks like this:

```
{
  "name": "package-b",
  "version": "0.0.1",
  "dependencies": {
    "fs-extra": "8.1.0"
  },
  "devDependencies": {
    "graphql": "14.5.8"
  }
}
```

after running ```npm install``` or similar from ```package-a```, ```package-b``` will be available in ```package-a```. ```fs-extra``` will be available to ```package-b``` and also directly from ```package-a``` if you're using npm or yarn (although it really shouldn't be which is why I like [pnpm](https://pnpm.js.org/)). However, ```graphql``` will never be installed because devDependencies are only installed for the root level package and should only be used for development of ```package-b```. In a situation like that, types from ```package-b``` that rely on types from ```graphql``` just end up as ```any```.

**Comment by jasonkuhrt** [comment]
@ssalbdivad Thanks for explaining. Can a peer dep be satisfied by the consumer supplying it as a dev dep? If so wouldn't that lead to triggering the classic "unmet peer dep requirement ..." warning during `npm install --production` time? If not, obviously being forced to bring in a runtime-unused dep is bad.

This scenario must be very common across the TS ecosystem. What are the established patterns around it?

**Comment by ssalbdivad** [comment]
@jasonkuhrt It seems like devDependencies do satisfy peerDependency requirements. When a user runs ```npm install --production```, there is no warning as long as the dependency is listed in devDependencies. I'll reiterate I don't think that makes any sense, but that does seem to be the behavior of ```yarn``` and ```npm```.  If you're interested, I would check out [rush](https://rushjs.io/) which is an open-source Microsoft project for managing monorepos. They've thought a lot about these issues and built a great solution, especially in conjunction with pnpm.

**Comment by jasonkuhrt** [comment]
Also related  https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies. 

@ssalbdivad in this case we might be technically ok because nexus is a peer dep and nexus makes graphql-js a peer dep. But it’s probably better to be explicit about it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
