### ISSUE TITLE
after update from 3.8 to latest

### ISSUE THREAD

**Issue by harmnot** [graphql-nexus/nexus-plugin-prisma#578]
finally I open issue because I have find the error everywhere and can't found any, 
I was using prismaObjectType before and it was deleted, right ? and change to t.model.id() and bla bla..... I follow that instructions, but it get error `Cannot read property 'id' of undefined` ? what is wrong ? and I can't use `makeSchame({
       plugins: [nexusPrismaPlugin()],
})` as well, it get red / error on my idea

**Comment by oscarteg** [comment]
@harmnot The latest version of nexus-prisma only works when you use the latest version of nexus. The latest version of nexus has the option for plugins. But, the latest version of nexus requires prisma 2 instead of prisma 1. So it is a whole chain you have to go to.

**Comment by oscarteg** [comment]
@harmnot https://github.com/prisma-labs/nexus-prisma/releases/tag/v0.4.1

**Comment by jasonkuhrt** [comment]
Thanks @Oscarteg

**Comment by oscarteg** [comment]
@jasonkuhrt No problem. Took me a couple of hours to figure out the same problem. Can you close the issue?
