### ISSUE TITLE
Update to support Prisma 2 preview 20

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/nexus-plugin-prisma#579]
#### what

- `@prisma/photon` `->` `@prisma/client`
- still try to import `@prisma/photon` too
	_to make migration path easier for Prisma <= 19 users_
- update `nexus-prisma` examples in prisma2 examples repo

**Comment by Weakky** [comment]
I'd suggest to keep trying to require `@prisma/photon` for a while, and add a warning giving indications on how to update

**Comment by justicejoe** [comment]
is this new one you working for added method "count" yet?

**Comment by SvitlanaShepitsena** [comment]
Looking forward.... cannot wait :-). Thank you for your hard work, guys!

**Comment by jasonkuhrt** [comment]
Hey everyone this is released in `0.7.0-next.2`. Please leave feedback, a stable release will be cut later this week if no major issues reported.
