### ISSUE TITLE
Error: Could not find Prisma Client JS in context (ctx.prisma)

### ISSUE THREAD

**Issue by heymartinadams** [graphql-nexus/nexus-plugin-prisma#587]
Updated to `nexus-prisma@0.8.0` (as well as `@prisma/client@2.0.0-preview020.3`) yet am receiving the following error:

`Error: Could not find Prisma Client JS in context (ctx.prisma)`

## index.js
```js
import { GraphQLServer } from 'graphql-yoga'
import { nexusPrismaPlugin } from 'nexus-prisma'
import { makeSchema } from 'nexus'
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
...
new GraphQLServer({
	schema: makeSchema({
		types: { ...types, ...resolvers },
		plugins: [nexusPrismaPlugin()]
	}),
	context: ctx => ({
		...ctx,
		prisma
	})
}).start()
```

**Comment by heymartinadams** [comment]
I should note, this error only occurs when client attempts to query server.

**Comment by Weakky** [comment]
Hey @heymartinadams, I unfortunately cannot reproduce your issue. Would you mind posting a small repro on a repository that I could use?

It's most likely something on your side. All the examples on the `nexus-prisma` repo + `prisma-examples` repo are now using the latest nexus-prisma and it's working fine.

I might still be wrong here, so a reproduction would be super helpful. Thanks a lot 🙏

**Comment by gnuzd** [comment]
Hi @Weakky, same issue here. Could you try to query the relationship?

**Comment by Weakky** [comment]
Running the following query on the `examples/blog` example:

```graphql
{
  people {
    id
    posts {
      id
      tags {
        id
      }
    }
  }
}
```

And everything works fine :/

**Comment by heymartinadams** [comment]
Ah, this error disappears when I stop using middlewares. Somehow, the `prisma` object isn’t recognized in the middleware function.

**Comment by gnuzd** [comment]
Hi @Weakky, 
Sorry, my bad. You right, everything works fine. Thanks

**Comment by jasonkuhrt** [comment]
@heymartinadams can you share a repro?

**Comment by heymartinadams** [comment]
@jasonkuhrt it’s quite massive. Happy to add you to the repo, though my co-founder is quite paranoid about sharing the codebase with non-employees, so can’t, sorry. 😞

**Comment by jasonkuhrt** [comment]
@heymartinadams Understandable, we'll try to repro based on your description on the examples in this repo when we have time.

**Comment by shanyu-e** [comment]
![image](https://user-images.githubusercontent.com/3265603/74251909-cf960480-4d27-11ea-803a-2fa31ba50b11.png)
I have the same question, the word should be `prisma` because of the update @heymartinadams

**Comment by heymartinadams** [comment]
I’m using `prisma = new PrismaClient()`, @shanyu-e. Thanks though.

FYI, it all appears to work now (even with middlewares) with `2.0.0-preview021`. Have no idea why. 🤷🏻‍♂️

Closing to reduce your overhead @Weakky, @jasonkuhrt. Btw, is it common practice for the developer who opened the issue to close it, or for the team to close the issue?

**Comment by jasonkuhrt** [comment]
> Closing to reduce your overhead @Weakky, @jasonkuhrt. Btw, is it common practice for the developer who opened the issue to close it, or for the team to close the issue?

@heymartinadams yep totally fine for you to close it :) We'll re-open if we feel otherwise (e.g. user drops his feature request but we still see value in it for others).

**Comment by gustawdaniel** [comment]
Should I use `graphql-yoga` or `apollo-server-express`?

**Comment by jasonkuhrt** [comment]
@gustawdaniel `apollo-server-express`
