### ISSUE TITLE
Dev mode migrations

### ISSUE THREAD

**Issue by Weakky** [graphql-nexus/nexus-plugin-prisma#592]
## Description

As dev mode was removed, we need to move away from dev/watch migrations.

## Proposal

When we detect the schema.prisma file was changed, prompt user to confirm that they're willing to migrate the db. During that period of time, the watcher should be paused and shouldn't trigger and restart.

Only when the user confirm and the migration is applied should the server restart

[Watch the prototype here](https://www.loom.com/share/9b907df398da4e95b10f45ef43eebfc4)

**Advantages of blocking prompt**

- Migrations are very long to run (because of the client generation). It might actually feel very slow to wait for minutes if several migrations are triggered while you're just editing one field
- Prevent from creating 3+ migrations files everytime a user updates his `schema.prisma`
- In case of a migration error, having a blocking prompt allows to "freeze" the user into that state until he actually resolves his schema issues. It basically prevents from going into weird state where a migration failed, but the runner restarts as if nothing happens

## Questions to solve

- What happens if user says "no" ?

**Comment by jasonkuhrt** [comment]
@Weakky why closed?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
