### ISSUE TITLE
Queries for camelCased models are failing

### ISSUE THREAD

**Issue by iherger** [graphql-nexus/nexus-plugin-prisma#594]
I just upgraded to the latest versions of prisma2/nexus-prisma and nexus.

After the upgrade, simple queries for camelCased models are failing, e.g.
```graphql
{
  passTypes {
    id
  }
}
```
The error is
```
"TypeError: Cannot read property 'findMany' of undefined",
"    at resolve (/xxxxx/node_modules/nexus-prisma/src/builder.ts:312:60)",
```

The same simple query with just lowercased models works fine, e.g.
```graphql
{
    passes {
    id
  }
}
```

Versions:
```
"@prisma/client": "^2.0.0-preview021",
"nexus": "^0.12.0-rc.9",
"nexus-prisma": "^0.9.0",
```

**Comment by BjoernRave** [comment]
can confirm this problem

**Comment by malekjaroslav** [comment]
I have the same issue

**Comment by jasonkuhrt** [comment]
Thanks for reporting. Hold off on the latest upgrade, will try to fix this weekend.

**Comment by sakhro** [comment]
Same problem 

```
TypeError: Cannot read property 'findOne' of undefined at fieldConfig.buildFieldConfig.resolve (..../node_modules/nexus-prisma/src/builder.ts:477:62)
```

**Comment by jasonkuhrt** [comment]
`0.9.1-next.1` (`next` dist tag) is available. If all is looking good, @Weakky or I will cut stable tomorrow.
