### ISSUE TITLE
'datamodel' is undefined when specifying output of datamodel generator

### ISSUE THREAD

**Issue by BenJeau** [graphql-nexus/nexus-plugin-prisma#606]
I am migrating from prisma1 to prisma2 and I had multiple Prisma instances, each having their own database. I am referring myself to the examples in this repo for the transition (more specifically to the **blog** example).

I have figured out that I need to specify an output for the generator in the datamodel file, specified [here](https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md#generators-optional).

By modifying the `schema.prisma` file to look like this
```prisma
generator prisma_client {
  provider = "prisma-client-js"
  output   = "./generated/client"
}
```
running `yarn generate:prisma`, and changing the imports of PrismaClient to import it from the correct path, aka the new "./generated/client" path, I am getting an error when running either `yarn dev or yarn generate:nexus`

```shell
./nexus-prisma/examples/blog/node_modules/nexus-prisma/src/dmmf/transformer.ts:33
    datamodel: transformDatamodel(document.datamodel),
                                           ^
TypeError: Cannot read property 'datamodel' of undefined
```

I also modified the typegenAutoConfig sources of `src/schema/index.ts` with
```ts
{
  source: path.join(
    __dirname,
    '../../prisma/generated/client/index.d.ts',
  ),
  alias: 'prisma',
},
```

How could I specify the datamodel or solve this problem?

**Comment by andersonba** [comment]
Try adding your custom path to the `nexusPrismaPlugin` options:

```javascript
  plugins: [
    nexusPrismaPlugin({
      inputs: {
        prismaClient: path.join(__dirname, '../../prisma/generated/client),
      },
    }),
  ],
```

**Comment by BenJeau** [comment]
Thanks @andersonba, this worked and fixed the problem!

**Comment by BenJeau** [comment]
Quick question, since I have two Prisma instances, I have two Prisma clients. Therefore would I specify both in the inputs of the `nexusPrismaPlugin` and also add it to `typegenAutoConfig`?
