### ISSUE TITLE
 Could not find field 'Mutation.undefined' on type Mutation

### ISSUE THREAD

**Issue by gabrielcolson** [graphql-nexus/nexus-plugin-prisma#650]
If I have a model with only one field in my schema and if that field is an autoincremented int, `nexus-prisma` throws an error.

For example, this fails:
```
model User {
  id Int @id @default(autoincrement())
}
```

While this does not:
```
model User {
  id Int @id @default(autoincrement())
  username String @unique
}
```

Fun fact, this does not fail either:
```
model User {
  id String @id @default(uuid())
}
```

The behavior is the same no matter how many models I add.

nexus-prisma version: 0.12.0
@prisma/cli version: 2.0.0-beta.2
@prisma/client version: 2.0.0-beta.2
@nexus/schema version: 0.13.1

Edit: This bug also occurs when the schema.prisma is empty

**Comment by xentobias** [comment]
+1

**Comment by aakashkag** [comment]
did you got any solution? I am facing same issue :(

**Comment by mattpengelly** [comment]
Also running into this issue and it's completely stopped our project.  Looking to switch to a non-prisma solution at this point.

**Comment by aakashkag** [comment]
I solved by removing tables which hold just id, 
Another solution to add some more column in table.

**Comment by mattpengelly** [comment]
I think you just solved our problem!  Thank you aakashkag!
