### ISSUE TITLE
Is it possible to use generated types in frontend?

### ISSUE THREAD

**Issue by Fivedark** [graphql-nexus/nexus-plugin-prisma#660]
I'm using Prisma2 with Nexus in a Next.js Typescript project. 

Is it possible to use the generated types also in frontend with apollo hooks for example?

I've tried something like this:
```
type StoreData = {
  store: NexusGenFieldTypes['Store']
}
const storeQuery = gql`
  query($slug: String!) {
    store(where: { slug: $slug }) {
      id
      slug
      name
      address {
        id
        streetAndNumber
        details
        city
        zipCode
      }
    }
  }
`
const { error, loading, data } = useQuery<StoreData>(storeQuery, {
  variables: { slug },
})
```
The type of `data` should now match the query result.
This is working for all scalars but not for relations. The `address` gets the type from Prisma (NexusGenRootTypes['Address'] which is Prisma.Address) and not the nexus generated type (NexusGenFieldTypes['Address']).

**Comment by moderndegree** [comment]
I believe you can import them like so:
```javascript
import { User } from "@prisma/client";
```
I was able to do this in a monorepo I am setting up.

EDIT: I just realized, you were referring to gql types. I was thinking TypeScript.

**Comment by Fivedark** [comment]
Thank you for your reply @moderndegree.

I mean TypeScript types that match my GraphQL types defined with Nexus. 

The generated Prisma types represent the data coming directly from the database. But with Nexus you can define more fields and got also the relations to other types, which are not included in the Prisma types.

**Comment by beeplin** [comment]
@Fivedark apollo codegen tool is what you need.

**Comment by Fivedark** [comment]
Thanks alot @beeplin for this advice. I will give apollo codegen a try, but I'm still thinking that Nexus could deliver these types too.

**Comment by beeplin** [comment]
@Fivedark nexus is a backend graphql provider, and apollo is a frontend graphql consumer supporting react, vue and ng. they make perfect match. it is hard to imagine using graphql in frontend but without apollo.

**Comment by beeplin** [comment]
apollo codegen generates not only base graphql types, but also complex embedded types for every query/mutation in your frontend components.

**Comment by Fivedark** [comment]
Thanks for this clarification @beeplin. 

I use Next.js and there backend and frontend are a little bit mixed up. So I had the idea that nexus could generate these types to, because it has all information required. But I see the point, that it is out of your scope and there are already other tools.

So I added graphql-codegen to my project to solve the task.
