### ISSUE TITLE
computedInputs can't be async

### ISSUE THREAD

**Issue by macrozone** [graphql-nexus/nexus-plugin-prisma#665]
if you make `computedInputs` return a promise, it does not get `awaited` and the function fails.

`computedInputs` should await promises before passing the input to prisma

**Comment by bennettrogers** [comment]
I just ran into this issue as well. I need to check the database via prisma before returning a value for my `computedInput`, but this doesn't seem possible at the moment.

The docs indicate that an async `computedInput` is allowed in the [`objectType` definition](https://nexusjs.org/nexus-plugins/prisma#complex-computed-graphql-fields), but they don't seem to be allowed in the `mutationType` crud function definitions.

**Comment by macrozone** [comment]
@bennettrogers i opened a PR: https://github.com/graphql-nexus/nexus-plugin-prisma/pull/795

it works perfectly for me so far
