### ISSUE TITLE
t.model.fieldname() gives error in VSCode: Expected 1 arguments, but got 0

### ISSUE THREAD

**Issue by HendrikJan** [graphql-nexus/nexus-plugin-prisma#668]
I am new to TypeScript, so it might well be that I miss something obvious.
VSCode shows the following error about some of the fields in my model.

    No argument for 'opts' was provided

It seems to have a problem with the DateTime and Enum fields

My code:

```typescript
import {objectType} from '@nexus/schema'

export const AcademicYear = objectType({
  name: 'AcademicYear',
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.status() // <-- enum gives error
    t.model.employee_hours()
    t.model.leave_hours()
    t.model.to_date() // <-- date gives error
    t.model.from_date() // <-- date gives error
  },
})
```

This error starts after running "npm run dev"

Package.json:
```json
{
  "name": "typescript-graphql",
  "scripts": {
    "start": "node dist/server",
    "clean": "rm -rf dist",
    "build": "npm -s run clean && npm -s run generate && tsc",
    "generate": "npm -s run generate:prisma && npm -s run generate:nexus",
    "generate:prisma": "prisma generate",
    "generate:nexus": "ts-node --transpile-only src/schema",
    "postinstall": "npm -s run generate",
    "initdb": "node database/init.js",
    "dev": "ts-node-dev --no-notify --respawn --transpileOnly src/server"
  },
  "dependencies": {
    "@nexus/schema": "0.13.1",
    "@prisma/client": "2.0.0-beta.5",
    "@types/node-fetch": "2.5.7",
    "apollo-server": "2.13.1",
    "chalk": "^4.0.0",
    "graphql": "15.0.0",
    "mysql2": "^2.1.0",
    "nexus-prisma": "0.13.0"
  },
  "devDependencies": {
    "@prisma/cli": "^2.0.0-beta.5",
    "@types/node": "14.0.5",
    "ts-node": "8.10.1",
    "ts-node-dev": "1.0.0-pre.44",
    "typescript": "3.9.3"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}
```

**Comment by HendrikJan** [comment]
I created a repository: https://github.com/HendrikJan/nexus-prisma-temp

Steps to reproduce:
- `docker-compose up' (this will already show the errors in the console)
- open a new terminal
- `docker-compose exec server bash`
- (inside docker) `npm run dev`

Now look in VSCode and see the errors in "/server/src/AcademicYear.ts"
![Screenshot from 2020-05-22 11-35-43](https://user-images.githubusercontent.com/2218920/82654156-96bbd480-9c20-11ea-9857-d71870d43ff5.png)

**Comment by HendrikJan** [comment]
By more closely following the example code, I was able to fix this problem.
So the bug seems to have been in my head and not in this repo (-:

**Comment by RikusWiehahn** [comment]
I had the exact same problem.

For anyone else stumbling on this in future, the fix is to make sure you include the new `objectType({` Model in you Schema.

For example: 
```js

export const schema = makeSchema({
  types: [Query, Mutation, AcademicYear],
  plugins...

```

**Comment by dev-msChoi** [comment]
i has same issue.
in my case
1. this column type is enum
2. if same column name exist on other table, this error
change column name unique, solve

**Comment by fullStackDataSolutions** [comment]
I have the same issue using Nexus-prisma-plugin, where everything should be autogenerated.

**Comment by jatins** [comment]
@HendrikJan I am getting the same error for `DateTime` fields. What worked for you?

**Comment by Manubi** [comment]
Did anyone fix it? :D

**Comment by dev-msChoi** [comment]
Nexus-prisma-plugin has error 
when using field name or table name end 's'
remove 's'

**Comment by fullStackDataSolutions** [comment]
I get the error for createdAt, updatedAt and some connections to other types. 

Anyone have a work around? Does it matter what version of Apollo you use? 

I'm using nexus-prism plugin
