### ISSUE TITLE
t.field only accepts 'BaseScalars' as type

### ISSUE THREAD

**Issue by williamluke4** [graphql-nexus/nexus-plugin-prisma#67]
Fails to compile with the following error
```
error TS2345: Argument of type '"UserAuth"' is not assignable to parameter of type 'BaseScalars'.
```
![clippy](https://user-images.githubusercontent.com/10773719/51843889-0370d880-2325-11e9-92f1-df06bde085f2.png)

```ts
export const UserAuth = prismaObjectType('UserAuth')
```
```graphql
type UserAuth {
  id: ID! @unique
  user: User @relation(name: "UserOnUserAuth")
  auth0UserId: String! @unique
  emailVerified: Boolean @default(value: false)
}
```

**Comment by Weakky** [comment]
Hey @williamluke4,

This is due to the typings from `nexus` that were not regenerated, probably because the server wasn't restarted.

Try using this command as your dev workflow `ts-node-dev --no-notify --respawn --transpileOnly ./src` is that's not already the case

**Comment by williamluke4** [comment]
Yep that solved it
