### ISSUE TITLE
Add hooks for CRUD nexus prisma fields

### ISSUE THREAD

**Issue by Mikastark** [graphql-nexus/nexus-plugin-prisma#684]
Hi everyone :)
Thanks for your amazing job with nexus and prisma. I want today propose a simple workaround for subscriptions and still allowing using autogenerated CRUD (since prisma v2 doesn't propose a built-in solution yet).

For now we can just use crud like this 
```typescript
t.crud.createOneUser()
```

But if you propose hooks, we will be able to add logic before/after the actual CRUD logic. Just like middlewares in fact. The after hook may provide all resolver args and add a new one "result" that is the returned value from the crud operation.
```typescript
t.crud.createOneUser({
  after: (result, parent, args, ctx) => {
    // add more logic
    ctx.pubSub({ //... })
  }
})
```

This will help people like me awaiting for realtime API but also for devs that need to expose CRUD AND add futher logic

**Comment by Weakky** [comment]
This feature was implemented in #674.

We've just released `nexus-prisma@0.15.0-next.1`.
You can try the feature by installing `nexus-prisma@next` right now. Feel free to report any bug related to it in here. I'll re-open the issue if needed 🙏
