### ISSUE TITLE
Nexus Schema Types don't recognize "Role" Prisma Type

### ISSUE THREAD

**Issue by felinto-dev** [graphql-nexus/nexus-plugin-prisma#689]
![Screenshot_234](https://user-images.githubusercontent.com/32253743/83955127-10a9ab80-a826-11ea-929a-d59c73a5d661.png)

![Screenshot_235](https://user-images.githubusercontent.com/32253743/83955137-1ef7c780-a826-11ea-8571-75483221dc9b.png)

![Screenshot_236](https://user-images.githubusercontent.com/32253743/83955143-2d45e380-a826-11ea-87b6-6a869e130bd1.png)

```
        const seller = {
          name: `${first_name} ${last_name}`,
          role: "RESELLER",
          cpf: `${number}`,
          email: `${email}`,
          loginName: `${nickname}`,
        }

        await ctx.prisma.seller.create({
          data: {
            ...seller,
            role: "RESELLER",
          },
        })
```

**Comment by Akxe** [comment]
This is a TS issue, to make it work as intended you need to say TS the `seller` is a read-only object. Other than that, you can inline the variable declaration to the `data` property, thus eliminating the read-only/mutable dilemma TS has.

```
const seller = {
  name: `${first_name} ${last_name}`,
  role: "RESELLER",
  cpf: `${number}`,
  email: `${email}`,
  loginName: `${nickname}`,
} as const;
```

**Comment by felinto-dev** [comment]
![Screenshot_239](https://user-images.githubusercontent.com/32253743/84183627-931eaf00-aa62-11ea-8d5c-aa65b189bdff.png)

![Screenshot_240](https://user-images.githubusercontent.com/32253743/84184017-0de7ca00-aa63-11ea-84fd-c483da7ed3b2.png)

Sorry, but I don't get your explanation. I changed a little the code, but I am still get error.

```
        const userPrisma = ctx.prisma.user.create({
          data: {
            ...user,
            accounts: {
              create: {
                nickname,
                platformUserId: mercadolibre_id.toString(),
                platform: "MERCADOLIBRE",
                details: userData,
              },
            },
            customer: {
              create: {},
            },
          },
        })
```

**Comment by Akxe** [comment]
@felinto-dev To fix this you can use `"MERCADOLIBRE" as const`.

**Comment by felinto-dev** [comment]
The problem was solved. 
I just made a small mistake when writing my schema.prisma. You can see it in the print. It's working fine now.

![download_1](https://user-images.githubusercontent.com/32253743/84206850-69777f00-aa86-11ea-9b6b-5c8d0dfbd71e.png)
