### ISSUE TITLE
npx nexus-prisma-generate fails "no valid 'prisma-client-dir' was found"

### ISSUE THREAD

**Issue by lterfloth** [graphql-nexus/nexus-plugin-prisma#71]
I updated all my dependencies and copied the typescript-auth (of the Prisma examples) while using a local docker container as the prisma endpoint.

Using "prisma deploy" runs "prisma generate" sucessfully but "npx nexus-prisma-generate" fails and logs the error "No valid 'prisma-client-dir' was found". The prisma-client folder is created sucessfully as well (../src/generated/prisma-client/).

I went through all the recent changes of the prisma exaples and can't find a solution to my problem. I assume there's something wrong with either the example or nexus prisma.

**Comment by Weakky** [comment]
Hi 👋,

Would you mind showing me what args are you passing to `nexus-prisma-generate`?

Thanks 🙌

**Comment by AMO-MTSY** [comment]
Hi
https://circleci.com/gh/prisma/prisma-examples/2798

**Comment by williamluke4** [comment]
Have you tried
```npx nexus-prisma-generate "./src/generated/prisma-client" "./src/generated/nexus-prisma.ts"```

**Comment by AMO-MTSY** [comment]
Working!
PS: graphql-auth prisma exemple uses "nexus": "0.9.2".

**Comment by lterfloth** [comment]
Works like a charm! The prisma example was updated and they forgot to update the prisma.yml and add the 2 new arguments. That lead to my confusion.  I notified them too and they fixed the issue as well. Thank you for helping!
