### ISSUE TITLE
Restore good old "skip" pagination argument

### ISSUE THREAD

**Issue by Mikastark** [graphql-nexus/nexus-plugin-prisma#710]
Hello there :)

I just updated `prisma-nexus` to version `0.15.0-next.5` and it seems you decided to remove `skip` from pagination args. It's a shame because all my Prisma projects use this approach for pagination and then all of them are broken now. I think `skip` is very useful and I bet I'm not the only one using it. Can you bring it back please ?

Anyway, you did a very great job with Prisma and Nexus thanks a lot :)

**Comment by jasonkuhrt** [comment]
Hey @MikaStark, thanks to @Gomah, we just shipped #709

**Comment by bstro** [comment]
@jasonkuhrt do you mean that `skip` should now be restored as a pagination argument? I'm on nexus-plugin-prisma`0.34.1` and the argument is missing. The only pagination-related args that I'm able to use from my graphql queries (using `t.crud` with `{pagination: true}`) are `before, after, first, last`.

**Comment by MikaStark** [comment]
@bstro skip argument have been replaced by « take ».
