### ISSUE TITLE
Failed Migration from "nexus-prisma" 0.15.0 to "nexus-plugin-prisma" 0.16.1: Prisma Client not usable

### ISSUE THREAD

**Issue by cimchd** [graphql-nexus/nexus-plugin-prisma#737]
I followed the docs for migration using `@nexus/schema` here: https://www.nexusjs.org/#/getting-started/migrate-from-nexus-schema.

I use `prisma` version 2.1.3 and `@nexus/schema` version 0.14.0

With `nexus-prisma` version 0.15.0 everything is fine.

If I change from  `nexus-prisma` to `nexus-plugin-prisma` version 0.16.1 everything seems to be fine (running prisma generate without errors, the folders `node_modules/.prisma/` and `node_modules/@prisma/client/` look normal).
But if I try to use the prisma client: 

```js
import { PrismaClient } from '@prisma/client';
const prisma = new Prismaclient();
console.log(prisma.dmmf);
```
I get the following error message:

``` 
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
api_1            | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
```

Interesting, while debugging: It seems, that as soon as I add `nexus-plugin-prisma` as a dependency, I get the error message above, even if I still use `nexus-prisma`.

We have a project setup that does not allow us to migrate to the complete nexus framework. So we only want to use the `@nexus/schema` and the prisma plugin. Is it still possible with `nexus-plugin-prisma`?

**Comment by Weakky** [comment]
Hey, did you make sure to uninstall all your prisma dependencies? This looks like you have multiple instances of the client installed as the Prisma dependencies are bundled with `nexus-plugin-prisma`.

> We have a project setup that does not allow us to migrate to the complete nexus framework. So we only want to use the @nexus/schema and the prisma plugin. Is it still possible with nexus-plugin-prisma?

You can still use `@nexus/schema` with `nexus-plugin-prisma`. In that case, import the schema plugin from `nexus-plugin-prisma/schema`.

Beware though, that even when using the schema plugin, **prisma dependencies will be bundled**.

**Comment by cimchd** [comment]
Thx @Weakky for your reply. I removed all node_modules folder in my project and tried it again and then it worked.
