### ISSUE TITLE
Autogenerated resolver types missing description property

### ISSUE THREAD

**Issue by Xetera** [graphql-nexus/nexus-plugin-prisma#752]
Resolvers for models allow for documenting the field in the graphql schema but currently it doesn't look like it's properly typed.
```js
t.model.stage_name({
  description: "The name an artist as commonly known by",
  alias: "stageName"
});
```

![working example](https://dreamcatcher.xetera.dev/😫🙅😈🙁🧖.png)

Despite actually working, you get an error saying `description` doesn't exist in `NexusPrismaScalarOpts` including every other non-scalar.

Edit: I seem to be having some other type issues with nexus-prisma-plugin, this issue might be related to that, I'll close if it is

**Comment by nayaabkhan** [comment]
Happening on my end as well. So probably something to be fixed. Happy to provide a PR if provided some assistance on the steps to fix it. 🙏🏼

So far my guess is that we need to add a field to the `NexusPrismaScalarOpts` for description.
