### ISSUE TITLE
Error on nexus generation

### ISSUE THREAD

**Issue by TomChv** [graphql-nexus/nexus-plugin-prisma#765]
Hello !

My project is in typescript
I use the "nexus-plugin-prisma" plugin in version: "^0.16.1".

I have an error when I want to generate my nexus schema.
It tells me I have to generate my client Prisma first... The problem being that I generate it successfully beforehand.

Dependencies
```json
  "dependencies": {
    "@nexus/schema": "^0.14.0",
    "@prisma/client": "^2.1.3",
    "@types/node": "^14.0.23",
    "apollo-server-express": "^2.15.1",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "http": "0.0.1-security",
    "nexus": "^0.25.0",
    "nexus-plugin-prisma": "^0.16.1",
    "ts-node": "^8.10.2",
    "ts-node-dev": "^1.0.0-pre.52",
    "typescript": "^3.9.6"
  },
  "devDependencies": {
    "@prisma/cli": "^2.1.3",
    "@types/multer": "^1.4.3",
    "body-parser": "^1.19.0",
    "multer": "^1.4.2"
  }
```
Error :

![error-nexus-generation](https://i.imgur.com/tixVvQf.png)

Then I saw a warning from nexus-plugin-prisma telling me to uninstall the dependencies "@prisma/cli" and "@prisma/client". But the problem persists... He can't find prisma now.

```json
"dependencies": {
    "@nexus/schema": "^0.14.0",
    "@types/node": "^14.0.23",
    "apollo-server-express": "^2.15.1",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "http": "0.0.1-security",
    "nexus": "^0.25.0",
    "nexus-plugin-prisma": "^0.16.0",
    "ts-node": "^8.10.2",
    "ts-node-dev": "^1.0.0-pre.52",
    "typescript": "^3.9.6"
  },
  "devDependencies": {
    "@types/multer": "^1.4.3",
    "body-parser": "^1.19.0",
    "multer": "^1.4.2"
  }
```

Error after uninstall @prisma/cli and @prisma/client :
![error-prisma](https://i.imgur.com/ISgTTzg.png)

**Comment by TomChv** [comment]
I found a solution !

Basically, when I install nexus-plugin-prisma, it automatically installs @prisma/client and @prisma/cli and nexus puts you a warning that you have to do "npm remove @prisma/client and @prisma/cli" . The problem is that it also removes the plugins in nexus-plugin-prisma/@prisma/client .... So you have to reinstall nexus-plugin-prisma by hand.

**Comment by hatchli** [comment]
Thank you @TomChv !

**Comment by jasonkuhrt** [comment]
And thanks @TomChv for the PR as well. Very much appreciated. I tweaked to be:

```
rm -rf node_modules
npm install
```

As I think that should be enough. If you know otherwise please let me know 🙏
