### ISSUE TITLE
Plugin is not working for Prisma v2.3.0

### ISSUE THREAD

**Issue by phillip055** [graphql-nexus/nexus-plugin-prisma#767]
After updating,, unable to build schema.

**Comment by ashih42** [comment]
I am having the same problem.  For now, I switched to using the deprecated `nexus-prisma@0.15.0` just to keep things running.

**Comment by AryanJ-NYC** [comment]
`nexus-plugin-prisma` now comes bundled with `@prisma/client` and `@prisma/cli` so be sure to run `yarn remove @prisma/client @prisma/cli && yarn install nexus-plugin-prisma`.

**Comment by kokokenada** [comment]
It looks like nexus-plugin-prisma (0.16.1) is still at Prisma 2.1... (right?) Is there any goals on how fast the bundle will stay up-to-date? (E.g. I'm waiting for a fix in the to-be-released Prisma 2.4)

**Comment by AryanJ-NYC** [comment]
You can use `yarn resolutions` to make sure you get 2.4 instead of 2.1 Visit https://nexusjs.org/meta/architecture#dependency-philosophy and scroll down to "Yarn resolutions to the rescue"

**Comment by phillip055** [comment]
Closing this issue, using canary channel

**Comment by kokokenada** [comment]
@AryanJ-NYC - does this force users into using yarn opposed npm?  Any plans to keep nexus-plug-prisma up-to-date?

**Comment by AryanJ-NYC** [comment]
@kokokenada Yes, it does.

I am not affiliated with nexus so cannot answer the second question.

**Comment by jasonkuhrt** [comment]
The plan is to keep the plugin up to date. Same day.
