### ISSUE TITLE
Upgrade to prisma 2.5.0

### ISSUE THREAD

**Issue by brielov** [graphql-nexus/nexus-plugin-prisma#798]
Prisma just released `2.5.0` with new features. It would be nice to bump to the newest version

**Comment by macrozone** [comment]
in particular would be nice to have case insensitive quering. I would immediatly ASAP add it to https://github.com/panter/ra-data-prisma

**Comment by hyochan** [comment]
Waiting for this!

**Comment by Blatty** [comment]
Just wondering, what's the current workflow internally at Prisma after every Prisma release? Would be good to always be up to date within the prisma ecosystem 📦

cc @Weakky @jasonkuhrt

**Comment by FjVillar** [comment]
@Blatty I thought the same, I was looking the last upgrade MR https://github.com/graphql-nexus/nexus-plugin-prisma/pull/775 to the 2.4.0. From what I see Prisma added improved types to their filters so in this plugin is necessary to replicate that and also make some tests to ensure they work fine. I would say that is easy to update this plugin, but it depends on what it's new on Prisma.

**Comment by jasonkuhrt** [comment]
Back from vacation, we're looking at this now

**Comment by VNadygin** [comment]
Waiting for it 🚀

**Comment by phillip055** [comment]
@jasonkuhrt mvp
