### ISSUE TITLE
undici dependency link broken

### ISSUE THREAD

**Issue by cyrus-za** [graphql-nexus/nexus-plugin-prisma#809]
When installing `nexus-plugin-prisma` 0.17.0 I get a error when it tries to install a dependency called `undici` via `git://github.com/mcollina/undici.git#e76f6a37836537f08c2d9b7d8805d6ff`

```sh
Couldn't find match for "e76f6a37836537f08c2d9b7d8805d6ff21d1e744" in "refs/heads/1.2.0-proposal,refs/heads/1.3-proposal,refs/heads/1.4-proposal,refs/heads/allow-throwing-handler,refs/heads/async2,refs/heads/avoid-servername,refs/heads/bench-echo,refs/heads/body-error-handler,refs/heads/buffer,refs/heads/busy-timeout,refs/heads/cork-tick,refs/heads/delvedor/add-353,refs/heads/delvedor/pool,refs/heads/delvedor/pool-share-tls-session,refs/heads/dispatch,refs/heads/doc-type,refs/heads/drain-stack,refs/heads/fast-pipeline-body,refs/heads/fast-socket,refs/heads/fast-socket2,refs/heads/fix-async-errors,refs/heads/fix-pipeline,refs/heads/fix-reset-pipeline,refs/heads/fix-test,refs/heads/get-head-body,refs/heads/idle-options,refs/heads/incoming-message-compat,refs/heads/info-trailers,refs/heads/invalid-server-response,refs/heads/llhttp,refs/heads/master,refs/heads/middleware,refs/heads/middleware2,refs/heads/move-core,refs/heads/no-async,refs/heads/onbody-callback,refs/heads/opaque,refs/heads/opt-parseHeaders,refs/heads/perf-test5,refs/heads/pipeline-destroy,refs/heads/pipeline-fast-dst,refs/heads/pool-abort,refs/heads/pool-aborted,refs/heads/pool-queue,refs/heads/proposal-1.1,refs/heads/refactor-request2,refs/heads/refactor11,refs/heads/refactor12,refs/heads/refactor2,refs/heads/request-timeout,refs/heads/request-timeout2,refs/heads/simplify,refs/heads/simplify-busy,refs/heads/test-parser,refs/heads/test-perf6,refs/heads/throw-expect,refs/tags/delete,refs/tags/elete,refs/tags/v1.0.0,refs/tags/v1.0.1,refs/tags/v1.0.2,refs/tags/v1.0.3,refs/tags/v1.1.0,refs/tags/v1.2.0,refs/tags/v1.2.1,refs/tags/v1.2.2,refs/tags/v1.2.4,refs/tags/v1.2.5,refs/tags/v1.2.6,refs/tags/v1.3.0,refs/tags/v1.3.1" for "git://github.com/mcollina/undici.git".
```

It appears that the repo has moved to the [nodejs](https://github.com/nodejs) org.

**Comment by cyrus-za** [comment]
After further digging, it seems that [@prisma/engine-core](https://www.npmjs.com/package/@prisma/engine-core) is the library that depends on `undici`. I will log an item in [prisma](https://github.com/prisma/prisma)

**Comment by cyrus-za** [comment]
Posted issue on prisma repo with more info: https://github.com/prisma/prisma/issues/3472

**Comment by Jolg42** [comment]
I posted the explanation and workaround here https://github.com/prisma/prisma/issues/3472#issuecomment-683757175

**Comment by cyrus-za** [comment]
Workaround works for me. Once this plugin switches to prisma 2.6 (after it released) this issue can be closed

**Comment by bb-art** [comment]
Still having this issue with version 0.19 (using prisma 2.7):

npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/nodejs/undici.git

**Comment by webbkyr** [comment]
This is also broken for me (our CI doesn't play nice with direct git dependencies). Prisma [has fixed this](https://github.com/prisma/prisma/blob/2.8.0/src/packages/engine-core/package.json#L48) in its latest release, `2.8.0`. 

Is it possible that we can bump this for the next release?

**Comment by Jolg42** [comment]
@webbkyr I don't know exactly when will be the next update, in the meantime you could use this workaround I think:

In your package.json, if you use yarn
```
{
  "name": "project",
  "version": "1.0.0",
  "dependencies": {
    "nexus-plugin-prisma": "...",
  },
  "resolutions": {
    "nexus-plugin-prisma/**/undici": "2.0.5"
  }
}
```

I didn't try it, so it possible it needs to be adjusted, here are the docs https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by Weakky** [comment]
Hey @webbkyr, as the framework support has now been dropped, there's unfortunately nothing anymore that we can do. Your only options are now:

- Either what @Jolg42 has proposed
- Update to the latest `nexus-plugin-prisma` version (which doesn't support the framework anymore)

Apologies for the inconvenience 🙏
