### ISSUE TITLE
Monorepo's not supported

### ISSUE THREAD

**Issue by sachaw** [graphql-nexus/nexus-plugin-prisma#840]
I have a basic monorepo configured as follows:

`package.json`
```typescript
{
  "private": true,
  "workspaces": [
    "client",
    "server"
  ]
}

```

`/server` contains an unmodified nexus install: `npx nexus@latest` with `nexus-plugin-prisma` configured.

by running `yarn && yarn build`
The build fails with the following type error:
`Cannot find name 'NexusPrisma'.`
upon checking, `nexus-plugin-prisma` did not generate any type definitions at all. If I move `/server` out of the monorepo, it builds fine.

**Comment by sachaw** [comment]
Likely related, I found that https://github.com/graphql-nexus/nexus-plugin-prisma/blob/989014b7f7882eeb48d1406412169429fee388cd/src/schema/builder.ts#L194
resolves (in my case) to `/home/sachaw/@types/typegen-nexus-plugin-prisma/index.d.ts`
which is out of the scope of my project

**Comment by sachaw** [comment]
Found a temp workaround:
add the following to `typeRoots`
`"../node_modules/@types"` to include types generated in parent folder (monorepo container)

**Comment by lockinmarv** [comment]
You could configure the outputs of `typegen` to resolve to your folder.
```js
nexusSchemaPrisma({
  outputs: {
    typegen: resolve(__dirname, './node_modules/@types/typegen-nexus-plugin-prisma/index.d.ts')
  }
})
```
The only problem I have is that the generate file has an `import * as Typegen from 'nexus-plugin-prisma/typegen'` but can't find the `nexus-plugin-prisma/typegen`. Any idea why? It seems that it doesn't exist, only `nexus-plugin-prisma/schema` exists.

EDIT: nvm related to #875 and fixed with https://github.com/graphql-nexus/nexus-plugin-prisma/pull/883

**Comment by Weakky** [comment]
Closing now as the issue is related to Nexus Framework which is now discontinued. You can read more about it here nxs.li/unframework/about

**Comment by lockinmarv** [comment]
I don't use Nexus Framework (only `nexus-plugin-prisma` which is not shut down) and the error exists there. Without the explicit definition of the typegen output, it can't find `NexusPrisma`.

**Comment by chadwhittaker** [comment]
> I don't use Nexus Framework (only `nexus-plugin-prisma` which is not shut down) and the error exists there. Without the explicit definition of the typegen output, it can't find `NexusPrisma`.

Did you ever figure out how to fix this? I'm having same issue. error TS2304: Cannot find name 'NexusPrisma'. I only get this error when I try to build on my Heroku server. Building locally works fine
