### ISSUE TITLE
Can't return associated records of deleted record

### ISSUE THREAD

**Issue by mohe2015** [graphql-nexus/nexus-plugin-prisma#851]
#### Nexus Report
```json
{
  "node": "v12.18.3",
  "os": {
    "platform": "linux",
    "release": "5.8.5"
  },
  "nexus": "^0.27.0-next.5",
  "plugins": [
    "nexus-plugin-prisma"
  ],
  "otherDependencies": {},
  "devDependencies": {},
  "hasAppModule": true,
  "packageManager": "npm",
  "errorsWhileGatheringReport": {
    "gettingLayout": null,
    "gettingPluginManifests": null
  }
}
```

#### Description
When deleting a record which has associated records nexus fails to return the deleted data if you request the associated record.

The actual problem is that there is a request for the data
```sql
SELECT `test`.`Round`.`id`, `test`.`Round`.`studentId` FROM `test`.`Round` WHERE `test`.`Round`.`id` = ? LIMIT ? OFFSET ?
```
after the data had been deleted.

#### Repro
The [README.md](https://github.com/mohe2015/nexus-bug1/blob/main/README.md) should contain all necessary steps.
https://github.com/mohe2015/nexus-bug1/

Btw this is a blocker for me so if there is a workaround I would love to hear about it.

**Comment by jasonkuhrt** [comment]
Hi @mohe2015 can you please create a new issue at https://github.com/graphql-nexus/nexus-plugin-prisma/issues/new

**Comment by justinkaseman** [comment]
Running into this as a blocker as well.
