### ISSUE TITLE
Upgrade Prisma to v2.8

### ISSUE THREAD

**Issue by jpalumickas** [graphql-nexus/nexus-plugin-prisma#865]
Current plugin version specifies Prisma 2.7 version.
Prisma 2.8 was released recently https://github.com/prisma/prisma/releases/tag/2.8.0

Also, maybe `@prisma` dependencies should be in `peerDependencies` to avoid version missmatch ?

**Comment by kldzj** [comment]
@jasonkuhrt Now that the framework is discontinued, the `@prisma` dependencies can be installed as peers, right? This'd also solve most bundle size issues we previously had when deploying Nexus Schema with the Prisma plugin to AWS Lambda. (Referring to [#776](https://github.com/graphql-nexus/nexus-plugin-prisma/issues/776#issuecomment-668103569))

**Comment by jasonkuhrt** [comment]
@kldzj yep

**Comment by jpalumickas** [comment]
@jasonkuhrt current `peerDependency` is strict to `2.7.0`, so maybe this ticket should not be closed 🙂 I think it should be less strict (maybe `>=2.7 <3` or `2.x`

**Comment by jasonkuhrt** [comment]
@jpalumickas there's a reason it is strict. Feel free to open a feature request to make it less strict. It will require more resources from us to test against a larger matrix of Prisma versions, and a codebase that has more conditional logic etc.

**Comment by jpalumickas** [comment]
@jasonkuhrt thanks for explaining, cheers! 👍
