### ISSUE TITLE
nexus-prisma-generate mkdir errors

### ISSUE THREAD

**Issue by donovanhiland** [graphql-nexus/nexus-plugin-prisma#87]
When running:

`npx nexus-prisma-generate --client generated/prisma-client --output generated/nexus-prisma`

If `generated/nexus-prisma` already exists an error is thrown. I expected this to be overwritten.

**Comment by Weakky** [comment]
Hey 👋,

The files **are** properly overwritten for me.

Could you please show me your error?

**Comment by suevalov** [comment]
I've got the same error. Here is stack trace:

```bash
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EEXIST: file already exists, mkdir 'packages/api/src/generated/nexus-prisma'
    at Object.fs.mkdirSync (fs.js:885:18)
    at main (/node_modules/nexus-prisma-generate/dist/index.js:49:10)
    at Object.<anonymous> (/node_modules/nexus-prisma-generate/dist/index.js:26:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
```

**Comment by colebemis** [comment]
I'm getting the same error:
```
EEXIST: file already exists, mkdir '/Users/colebemis/projects/dasher-demo/backend/src/__generated__/nexus-prisma'
```

Here's the pull request that introduced the issue: https://github.com/colebemis/dasher/pull/24

**Comment by Weakky** [comment]
Hey,

This was never reproduced on my OS (macOS Mojave). As it should not throw anyway if the folder already exists, I have ignored that exception (https://github.com/prisma/nexus-prisma/commit/e72370a42c5125000558242662721a0700ab199f as suggested here https://stackoverflow.com/a/21196961/10256275)

Please, try using `nexus-prisma-generate@0.3.1` (or if you're using npx, it should use the latest version anyway)

**Comment by Weakky** [comment]
Closing, feel free to re-open if this still occurs to you.
