### ISSUE TITLE
Typegen artifact generated outside node_modules

### ISSUE THREAD

**Issue by adarnon** [graphql-nexus/nexus-plugin-prisma#873]
Commit f8a017c3bf72243bb699950b779572834e60af2c for version 0.20 renamed many files.
Namely, it moved `src/schema/builder.ts` to `src/builder.ts`.
However, when `shouldGenerateArtifacts` is `true`, the default output path is still `path.join(__dirname, '../../../@types/typegen-nexus-plugin-prisma/index.d.ts')`.
As a result, when I try to generate artifacts, the @types directory is generated in my project's root dir, instead of `node_modules`.
As a temporary workaround, the output path can be overridden through the `outputs.typegen` option.

**Comment by dusanmarsa** [comment]
Temporary solution didn't work for me. Can you provide code example of the workaround?

**Comment by uncvrd** [comment]
I defined a `typegen` output, 

```
  outputs: {
    typegen: join(__dirname, 'generated/nexusTypes.gen.ts'),
  },
```

When I run, it creates the following in my root directory: `@types/typegen-nexus-plugin-prisma/index.d.ts` and a `generated/nexusTypes.gen.ts` file, both are slightly different and shouldn't my custom output overwrite the plugin's ability to create the default @types folder in my root anyways?..any updates?

**Comment by adarnon** [comment]
Make sure you also override the plugin's `outputs.typegen` in the `nexusSchemaPrisma()` call, not just in the `makeSchema()` call.

**Comment by jawosis** [comment]
Could you please show a complete code example of your schema.ts file to  better understand how it should work?
