### ISSUE TITLE
missing typegen file in module

### ISSUE THREAD

**Issue by JustinVoitel** [graphql-nexus/nexus-plugin-prisma#875]
### Description
When generateing the typegen from the plugin, the first line in `node_modules/@types/typegen-nexus-plugin-prisma/index.d.ts` 
says: `import * as Typegen from 'nexus-plugin-prisma/typegen'`, but its missing from the module. This results into nexus-plugin-prisma not finding the corresponding types

### Possible fixes
1. either change the path in the typegen in index.d.ts to `nexus-plugin-prisma/dist/typegen/static`
2. or add the file typegen.js to the modules root with content: `module.exports = require('./dist/typegen/static')`

doing either of these above fixes the typings in my project

### Additional Infos
    operating system: windows 10 wsl2
    versions for
        node v14.8.0
        npm 6.14.7
        @nexus/schema 0.16.0
        nexus-plugin-prisma 0.20.0
        @prisma/client & cli 2.7.0

**Comment by heibel** [comment]
Affected as well. Working around it with `sed -i '' 's/nexus-plugin-prisma\/typegen/nexus-plugin-prisma\/dist\/typegen\/static/g' /path/to/output.d.ts`

**Comment by lewebsimple** [comment]
I can confirm changing the generated import to `nexus-plugin-prisma/dist/typegen/static` works with the following versions (as well as GraphQL 14 / 15) :
```
"@nexus/schema": "^0.16.0",
"nexus-plugin-prisma": "^0.20.0",
"@prisma/client": "~2.7.1"
"@prisma/cli": "~2.7.1"
```
The PR I submitted should work without breaking anything I ~~think~~ hope.

**Comment by Slmii** [comment]
idk why but my `@types/typegen-nexus-plugin-prisma/index.d.ts` is being generated in the root of the project and not in `node_modules`. Even if I change the import there it'll auto change back to the old value.

I deleted the `node_modules` and `package-lock.json`, did a fresh install and then run the command `prisma generate`. Im using:
```
"@nexus/schema": "^0.16.0",
"@prisma/client": "2.7.0",
"@prisma/cli": "2.7.0",
"nexus-plugin-prisma": "^0.20.0",
```
