### ISSUE TITLE
prismaObjectType does not create new objectType if type does not exist.

### ISSUE THREAD

**Issue by BenoitRanque** [graphql-nexus/nexus-plugin-prisma#88]
`prismaObjectType` works fine if the underlying `objectType` already exists. If it does not, an error is thrown.
"Must select a GraphQLObjectType, saw <TYPE NAME> which is undefined"
It works fine when switching to `objectType` instead for new objects.

Is this intended behavior? if so maybe update message:

"Must select a GraphQLObjectType, saw <TYPE NAME> which is undefined. Are you trying to create a new type? If so use objectType instead of prismaObjectType"

**Comment by Weakky** [comment]
Hey, suggestion taken, this is fixed and is now available under `nexus-prisma@0.2.0`.
Bare in mind that there are quite lots of breaking changes, although we haven't followed semver because this isn't yet officially released
