### ISSUE TITLE
[FEATURE] MULTIPOLYGON type from mysql

### ISSUE THREAD

**Issue by Akxe** [graphql-nexus/nexus-plugin-prisma#903]
This issue is not only about the fact, that nexus does not have the `MULTIPOLYGON` type. **I am wondering if I can transform `JSON` into some more restricting type!**
-----

I would like to have `MULTIPOLYGON` in my DB.

Since JSON is the closest thing I could think of, I started there.

```ts
import { scalarType } from '@nexus/schema';

export type Point = [number, number];
export type Polygon = [[number, number], [number, number], [number, number], ...[number, number][]];
export type MultiPolygon = [Polygon, ...Polygon[]];

export const MULTIPOLYGON = scalarType({
	name: 'MultiPolygon',
	asNexusMethod: 'MULTIPOLYGON',
	description: 'Custom definition od multi-polygon',
	serialize(value: any): string {
		return JSON.stringify(value);
	},
	parseValue(value: any): MultiPolygon {
		return JSON.parse(value);
	},
});

export const SelectionPolygon = objectType({
	name: 'SelectionPolygon',
	definition(t) {
		t.model.title();
		t.model.path(MULTIPOLYGON);
	},
});
```

But this got me nowhere near the wanted result:
```graphql
type SelectionPolygon {
  MultiPolygon: Json!
  title: String!
}
```

I would also like to create a mutation with this type. It should look like this:
```graphql
type Mutation {
  createSelection(polygons: MULTIPOLYGON): SelectionPolygon!
}
```

**Comment by Weakky** [comment]
Hey @Akxe, it looks like it's not documented but have you tried using the `scalars` option when configuring the plugin? Here's what the js docs say:

![image](https://user-images.githubusercontent.com/25233379/100632506-2b6c6100-332d-11eb-8760-b9861d0a1d09.png)

Assuming you are using the `MultiPolygon` type in your Prisma Schema, you should normally be able to do:

```ts
{
  scalars: {
    MultiPolygon: YourGraphQLJsScalarType
  }
}
```

**Comment by Akxe** [comment]
@Weakky I did, but I could not get it to work... It might be possible thought...
