### ISSUE TITLE
Match this repo version with prisma version

### ISSUE THREAD

**Issue by Mikastark** [graphql-nexus/nexus-plugin-prisma#904]
Hello everyone :)
Thanks for all your amazing work. Today I want to propose to unify this repo version with prisma as it depends on it.

At this issue time, prisma latest release is 2.9.0, why not set nexus-plugin-version version to 2.9.0 ? It will be easier to know which prisma version is compatible. And for fixes and minor improvements you can increase the third number (2.9.1 for example).

**Comment by the-simian** [comment]
This would have actually saved me a lot of time today, so I'd love to see this, personally

**Comment by jasonkuhrt** [comment]
This plugin follows semver and has its own feature set. It may be compatible with multiple versions of Prisma in the future.
