### ISSUE TITLE
xs.reduce is not a function on server startup

### ISSUE THREAD

**Issue by gmencz** [graphql-nexus/nexus-plugin-prisma#915]
I get the following error when I run the server:
```
TypeError: xs.reduce is not a function
    at Object.exports.indexBy (node_modules/nexus-plugin-prisma/src/utils.ts:66:15)
    at new DmmfDocument (node_modules/nexus-plugin-prisma/src/dmmf/DmmfDocument.ts:30:26)
    at Object.exports.getTransformedDmmf (node_modules/nexus-plugin-prisma/src/dmmf/transformer.ts:16:20)
    at new SchemaBuilder (node_modules/nexus-plugin-prisma/src/builder.ts:256:7)
    at Object.build (node_modules/nexus-plugin-prisma/src/builder.ts:175:19)
    at Object.onInstall (node_modules/nexus-plugin-prisma/src/plugin.ts:46:62)
    at node_modules/@nexus/schema/src/builder.ts:657:44
    at Array.forEach (<anonymous>)
    at SchemaBuilder.beforeWalkTypes (node_modules/@nexus/schema/src/builder.ts:651:18)
    at SchemaBuilder.getFinalTypeMap (node_modules/@nexus/schema/src/builder.ts:741:10)
```
Versions:
- nexus-plugin-prisma: `0.22.0`
- @prisma/client: `2.10.0`
- @nexus/schema: `0.16.0`

**Comment by abelchee** [comment]
https://github.com/graphql-nexus/nexus-plugin-prisma/pull/913 may fix this issue?

**Comment by ghost** [comment]
Also having this problem. Keeping an eye on this and 913. Thanks for opening the issue, I thought I was doing something wrong.

- nexus-plugin-prisma: `0.22.0`
- @nexus/schema: `0.16.0`
- @prisma/client: `2.10.0`

**Comment by SondreODahl** [comment]
Also having this problem, but with @prisma/client version `2.9.0`.

**Comment by gmencz** [comment]
I've performed a clean install but the issue persists.

**Comment by MitchellMonaghan** [comment]
I encountered this issue when using one of the prisma graphql examples (https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql). It worked for me after updating dependencies to the newest packages.

OLD
"@nexus/schema": "0.16.0",
"@prisma/client": "^2.8.1",
"nexus-plugin-prisma": "^0.21.0"

NEW
"@nexus/schema": "^0.17.0",
"@prisma/client": "^2.10.0",
"nexus-plugin-prisma": "^0.23.0"

**Comment by gmencz** [comment]
@MitchellMonaghan Thanks! Updating dependencies to the latest seems to fix it.

**Comment by ndom91** [comment]
Was having the same issue, with the same dep versions as @MitchellMonaghan. Upgrade also cleared it up :+1:

**Comment by fullStackDataSolutions** [comment]
I'm having the same issue: 
"@nexus/schema": "^0.18.0",
"@prisma/client": "^2.12.0",
"nexus-plugin-prisma": "^0.24.0",

There has to be a bug somewhere in this library.

**Comment by mohsinamjad** [comment]
why this issue is closed ?  
still having issues in 2.10.0, I think there should be clearly mentioned somewhere which versions of different module works together, it's really hard to hit and try different versions in the hope that it'll fix the issue.
