### ISSUE TITLE
Prisma 2.10.1 Peer Dependency

### ISSUE THREAD

**Issue by adarnon** [graphql-nexus/nexus-plugin-prisma#924]
Prisma was just updated to 2.10.1 with some important bug fixes, but the current nexus-plugin-prisma only declares peer dependency support with 2.10 explicitly. Can that be fixed? Is there a reason why the dependency doesn't support bugfix increases?

**Comment by darrylyoung** [comment]
Yeah, I also noticed this today. I get that there's a bit of a complicated setup but it seems like with every release of Prisma _or_ this package, there's a period of time between where people get caught in situations like this and issues have to be created.

**Comment by nhuesmann** [comment]
I'd appreciate this as well. Right now to avoid seeing the warning every time the server reloads I'm just editing nexus-plugin-prisma's package.json in node modules.

**Comment by jasonkuhrt** [comment]
Now obsolete by 8d75274fc4e969409155acabca6a03c7e34243ad
