### ISSUE TITLE
Ability to selectively disable nested create/connects?

### ISSUE THREAD

**Issue by colinhacks** [graphql-nexus/nexus-plugin-prisma#95]
I LOVE being able to easily create "derived types" in my GraphQL schema from my Prisma models. The hide/filter options and the ability to add additional custom fields is glorious. To do this before, I had to duplicate and modify my Prisma schema's AST.

Another major divide between the Prisma Client api and a typical GraphQL server is the ability to do arbitrarily nested writes with `create` and `connect`. It would be great if we could enable/disable these two options selectively on each relational field in our schema.

As a proposed API:

```
export const User = prismaObjectType({
  name: 'User',
  definition(t) {
    t.prismaFields([{ 
      name: 'posts', 
      args: ["published"], 
      nestedCreate: false, 
      nestedConnect: false 
    }])
  },
})
```

Without this, the ability to just "drop in" `createUser` and `deleteUser` from our Prisma API isn't useful, since we'd be giving the client free rein to nestedly create/connect/update/disconnect things in our database (assuming we pass the `createUser` parameters straight through to Prisma without any validation).

I figure it might be hard to implement this, since mutations aren't implemented in a nested way like queries. Any other ideas for how to validate nested arguments?

**Comment by Weakky** [comment]
Hey, thanks for the great feedback !

I'll post a GH issue later today with something that might address your issue and others.
We basically think there's room to transform the schema at "build time" once #86 lands.
That would reduce the runtime overhead, while also giving you autocompletion for the aliased fields that you might have transformed etc etc.

In the meantime, it's already possible to do what you want to do, it's just a bit more verbose.

`nexus-prisma` exposes all the graphql types required to have a working schema by default.
But you can override these types by simply defining them.

eg:

```graphql
type Mutation {
  createUser(data: UserCreateInput!): User!
}

input UserCreateInput {
  email: String!
  name: String
  posts: PostCreateManyWithoutAuthorInput
}
```

```ts
export const UserCreateInput = prismaInputObjectType({
  name: 'UserCreateInput',
  definition(t) {
    t.prismaFields(['email', 'name']) // Do not expose `posts` fields from the create input
  }
}}
```

Also, as mentioned here #90, now that we are code-first, there's a big room for function/object composition. As Prisma has normalized names for its types, you could probably make a simple function to automate that job once 🙌

**Comment by colinhacks** [comment]
@Weakky thanks, this makes sense. 

This would be a lot easier if there was a shorthand way to pass through all scalar fields. Proposed API:

```
export const UserCreateInput = prismaInputObjectType({
  name: 'UserCreateInput',
  definition(t) {
    t.scalars() // Expose all scalar fields
  }
}}
```

Then it would be trivial to add in the relational fields I care about for each query. Is there any simple way to do this now?

Unrelated note: I'm having trouble getting `t.prismaFields(["*"])` to work in my Typescript project. Any ideas?

**Comment by colinhacks** [comment]
Or, if you could provide extra type information to a filter function, this would be really easy.
```
export const UserCreateInput = prismaInputObjectType({
  name: 'UserCreateInput',
  definition(t) {
    t.prismaFields({
      filter: (fields: Field[])=>{
        // Field has `name` and `type` properties
        return fields.filter(field => ['String', 'Int', 'Float', 'Boolean'].includes(field.type))
      }
    }) // Expose all scalar fields
  }
}}
```
