### ISSUE TITLE
Support for prisma 2.11.0

### ISSUE THREAD

**Issue by tomasholicky** [graphql-nexus/nexus-plugin-prisma#957]
We use nexus-plugin-prisma and we have this issue [https://github.com/prisma/prisma/issues/3892](url) on current version of prisma (2.10.0) and we need to update to 2.11.0.

Could you increase it?

Thank you.

**Comment by jasonkuhrt** [comment]
Coming soon

**Comment by jasonkuhrt** [comment]
closed by 8d75274fc4e969409155acabca6a03c7e34243ad
