### ISSUE TITLE
Function that returns promises are not allowed in Nexus FieldResolver typings

### ISSUE THREAD

**Issue by LennardWesterveld** [graphql-nexus/nexus-plugin-prisma#958]
Does anyone know how to override FieldResolver in typescript?
I wanted to use a model class that returns the fields only when they are requested so I wrapped them in functions. See the sandbox for a fully working example. Remove the ts-ignore lines in schema.ts to see the errors.

I got the following error in typescript:
```
Error:(73, 13) TS2322: Type '() => Promise<string>' is not assignable to type 'string'.
```
and
```
Type 'TestModel' is not assignable to type 'MaybePromise<{ hello?: string; hello2?: string; }>'.
  Type 'TestModel' is not assignable to type '{ hello?: string; hello2?: string; }'.
    Types of property 'hello' are incompatible.
      Type '() => string' is not assignable to type 'string'.
```

See sandbox: https://codesandbox.io/s/sandbox-nexus-promise-error-3ddfq?file=/src/schema.ts

Question from slack: https://prisma.slack.com/archives/CM2LEN7JL/p1605552347363600

**Comment by jasonkuhrt** [comment]
I didn't see the type errors in that code sandbox. Tried forking and still didn't. Any tips? I'll try to find time to bring it down locally.

**Comment by LennardWesterveld** [comment]
Hi @jasonkuhrt you must remove all the lines below in schema.ts and then you have a server icon on the left bar and then you see Control Container  "Restart Sandbox" and "Restart Server" will also help some times. (and don't forget to save the file with control + s or apple +s)
```
      // @ts-ignore
```

Otherwise, you can run in terminal: `npm run lint:tsc` when you have removed the lines.

Then you get the following message:
```
src/schema.ts:34:9 - error TS2322: Type '() => Promise<string>' is not assignable to type 'string'.

34         hello: getExampleData("hello"),
           ~~~~~

src/schema.ts:35:9 - error TS2322: Type '() => Promise<string>' is not assignable to type 'string'.

35         hello2: getExampleData("hello2")
           ~~~~~~

src/schema.ts:40:22 - error TS2322: Type 'TestModel' is not assignable to type 'MaybePromise<{ hello?: string; hello2?: string; }>'.
  Type 'TestModel' is not assignable to type '{ hello?: string; hello2?: string; }'.
    Types of property 'hello' are incompatible.
      Type '() => string' is not assignable to type 'string'.

40       resolve: () => new TestModel()
                        ~~~~~~~~~~~~~~~

  node_modules/@nexus/schema/dist/typegenTypeHelpers.d.ts:67:88
    67 export declare type FieldResolver<TypeName extends string, FieldName extends string> = (root: RootValue<TypeName>, args: ArgsValue<TypeName, FieldName>, context: GetGen<'context'>, info: GraphQLResolveInfo) => MaybePromise<ResultValue<TypeName, FieldName>>| MaybePromiseDeep<ResultValue<TypeName, FieldName>>;
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.


Found 3 errors.
```

**Comment by jasonkuhrt** [comment]
The solution is to configure the backing types. Here's your example forked and fixed.

https://codesandbox.io/s/sandbox-nexus-promise-error-forked-80tm7?file=/src/schema.ts

Thanks for creating that, was helpful here to have that!
