### ISSUE TITLE
New way to define nullable and list in queryField or mutationField?

### ISSUE THREAD

**Issue by hyochan** [graphql-nexus/nexus-plugin-prisma#972]
I've just upgraded to `nexus-plugin-prisma@0.25.0` and doing migration as suggested.
I migrated my code on arguments and models but I can't find a clue on migrating `queryField` and `mutationField`.

Say I have below queryField.

```
export const notifications = queryField('notifications', {
  type: 'Notification',
  nullable: false,
  list: true,

  args: {
    userId: stringArg(),
  },

  resolve: (parent, { userId }, ctx) => {
    return ctx.prisma.notification.findMany({
      where: {
        userId,
      },
    });
  },
});
```

How can I remove `nullable` and `list` here? It keeps asking me to remove it but I don't see any alternative here.

**Comment by Mikastark** [comment]
You should use wrapper functions ;)

```ts
export const notifications = queryField('notifications', {
  type: nonNull(list(nonNull('Notification'))),
  args: {
    userId: 'String',
  },
  resolve: (parent, { userId }, ctx) => {
    return ctx.prisma.notification.findMany({
      where: {
        userId,
      },
    });
  },
});
```

**Comment by hyochan** [comment]
> You should use wrapper functions ;)
> 
> ```ts
> export const notifications = queryField('notifications', {
>   type: nonNull(list(nonNull('Notification'))),
>   args: {
>     userId: 'String',
>   },
>   resolve: (parent, { userId }, ctx) => {
>     return ctx.prisma.notification.findMany({
>       where: {
>         userId,
>       },
>     });
>   },
> });
> ```

That did the trick thanks.
